### ISSUE TITLE
Any use of `ddev config` automatically changes a project type from 'php' to the discovered codebase type

### ISSUE THREAD

**Issue by dnaber-de** [ddev/ddev#4403] opened 2022-11-24 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

(Skipped the diagnostics for now because this looks like intended but inconvenient behavior than a bug, but I'll add it if you think it is required, also I asked some colleagues if they can reproduce so I assume this is unlikely an issue related to my system) 

### Description

I am working mostly with WordPress project but in contrast to the suggested installation these applications are entirely build with Composer, for example by using a plugin like [WP Starter](https://github.com/wecodemore/wpstarter). So I do want to have the project type set to `php` because the `wp-config.php` is customized.

Now whenever I run a `ddev config` command, for example to change the PHP version, DDEV automatically sets the project type to `wordpress` unless I explicitly add the command parameter.

### Expected Behavior

I would expect `ddev config` to change the project type only if I explicitly add it as parameter.

### Actual Behavior

`ddev config` changes the project type to `wordpress` even if `--project-type` is not mentioned.

### Steps To Reproduce

Run the following commands in an empty (temporary) directory:

Create a new, empty DDEV project:

    ddev config --project-name project-type-issue --project-type php --php-version 8.0 --docroot public --create-docroot

Download WordPress core to the docroot:

    ddev exec wp core download --path=/var/www/html/public

Run DDEV config to update PHP version:

    ddev config --php-version 8.1

Now project-type has changed to `wordpress` in `.ddev/config.yaml`

Cleanup everything:

    ddev delete -O

**Comment by rfay** [comment] 2022-11-24 15:06
I agree this is a bug, and easy to recreate.

Only happens with project type 'php', won't happen if you have the wrong/different project type that is not 'php'. 

Here's the reason: https://github.com/drud/ddev/blob/078e1c0a661af76503a412b566391875b4005456/cmd/ddev/cmd/config.go#L446

It just seems to me like it's in error, but there could be side-effects of changing it. 

Want to try a PR?

**Comment by dnaber-de** [comment] 2022-11-28 09:04
> Want to try a PR?
Yes, sure but please don't expect this to happen before the end of the month.

**Comment by rfay** [comment] 2022-11-28 14:08
That's what I would think. First set of parens is not necessary.

**Comment by rfay** [comment] 2023-01-06 18:22
I think this is a duplicate of
* #1919

**Closed** 2023-07-04 18:08 UTC
