### ISSUE TITLE
flag to skip post-import-db-* hooks when using import-db

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6185] opened 2024-05-15 14:53 UTC
A colleague asked me about this and I was surprised to not find a native way of doing it.

I wonder if this is something logical to add?

**Comment by rfay** [comment] 2024-05-15 16:09
This would be a duplicate of
* https://github.com/ddev/ddev/issues/2129
true?

**Comment by hanoii** [comment] 2024-05-15 16:39
True

**Closed** 2024-05-15 16:39 UTC
Labels: enhancement

**Comment by rfay** [comment] 2024-05-15 17:09
#2129 seems like a modest effort and right up your alley for a contribution :)

**Comment by hanoii** [comment] 2024-05-15 17:33
I'll take a look
