### ISSUE TITLE
Drupal 9+, mysql database type, snapshot restore gets "unable to SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED"

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4933] opened 2023-05-19 17:55 UTC
Raised in https://stackoverflow.com/questions/76283615/ddev-overwrites-transaction-isolation-level-set-in-database :

### Expected Behavior

`ddev snapshot restore` should not encounter errrors

### Actual Behavior

With projects of type `drupal9` and `drupal10`, on database types mysql:5.7 and mysql:8.0, when you `ddev snapshot restore` you'll get output like:

`
unable to SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED: stdout='', stderr='', err=ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-d9 docker-compose -f /Users/rfay/workspace/d9/.ddev/.ddev-docker-compose-full.yaml exec -T db bash -c set -eu && ( mysql -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;" 2>/dev/null)', action='[exec -T db bash -c set -eu && ( mysql -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;" 2>/dev/null)]', err='exit status 1', stdout='', stderr=''
`

### Steps To Reproduce

```
ddev config --database=mysql:5.7
ddev start
ddev snapshot
ddev snapshot restore --latest
```

### Anything else?

Everything is fine after a `ddev restart`; the admin/reports/status page reports no trouble. So this is not a huge problem.

**Comment by rpkoller** [comment] 2023-05-19 23:14
Just for reference a brief summary of the info i've exchanged with @rfay on discord already. 

I've tested on drupal 10.1.0-beta1. 

mariadb 10.4 - unable to reproduce `ddev snapshot restore --latest`works without any error. 
mariadb 10.5 - unable to reproduce `ddev snapshot restore --latest`works without any error. 
mysql 8.0 - unable to reproduce `ddev snapshot restore --latest`works without any error. 
mysql 5.7 - the problem is reproducible consistently. after `ddev snapshot restore --latest` the db is set to `REPEATABLE-READ`. entering `ddev mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED"` sets the db to `READ COMMITTED` . 

when i try to run the same with the default user and pw for ddev db's i get an error: 

```
$> ddev mysql -udb -pdb -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED"    
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Failed to run mysql -udb -pdb -e SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED: exit status 1
```

**Comment by rfay** [comment] 2023-05-19 23:49
Unfortunately the simple fix doesn't seem to solve it. 

Changing the code to `Cmd:       `mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;"` still results in:

`unable to SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED: stdout='', stderr='', err=ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-d9 docker-compose -f /Users/rfay/workspace/d9/.ddev/.ddev-docker-compose-full.yaml exec -T db bash -c set -eu && ( mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;" 2>/dev/null)', action='[exec -T db bash -c set -eu && ( mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;" 2>/dev/null)]', err='exit status 1', stdout='', stderr=''`

But after the restore I am still able to:
`ddev mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;"`

**Closed** 2023-05-21 18:02 UTC
