### ISSUE TITLE
Composer create does not pass "--no-interaction" flag for "post-create-project-cmd" (Craft CMS)

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev#6246] opened 2024-05-25 13:31 UTC
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>
https://gist.github.com/mandrasch/9c5093ae8407a877f0b3859ab7b3842d
</details>

### Expected Behavior

Craft CMS has the following (https://github.com/craftcms/craft/blob/5.x/composer.json) `post-create-project-cmd`:

```
 "scripts": {
    "post-create-project-cmd": [
      "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\"",
      "@php -r \"unlink('composer.json');\"",
      "@php -r \"rename('composer.json.default', 'composer.json');\"",
      "@composer dump-autoload -o",
      "@php craft setup/welcome"
    ]
  }
  ```
  
 I want to run an install without interaction, therefore I want to use the following
  
 `ddev composer create -y --no-scripts --no-interaction craftcms/craft`
 
 with DDEV v.1.21.3 (since post-create-cmd is executed now)

### Actual Behavior

Executing  `ddev composer create -y --no-scripts --no-interaction craftcms/craft` get's stuck at this screen with a prompt:

![image](https://github.com/ddev/ddev/assets/777278/f51161d0-29e1-418a-b703-b4235cd13956)

Console output: 

```
Executing composer command: [composer run-script post-create-project-cmd]
 
> @php -r "file_exists('.env') || copy('.env.example.dev', '.env');"
> @php -r "unlink('composer.json');"
> @php -r "rename('composer.json.default', 'composer.json');"
Generating optimized autoload files
Generated optimized autoload files containing 5444 classes
> @php craft setup/welcome

   ______ .______          ___       _______ .___________.
  /      ||   _  \        /   \     |   ____||           |
 |  ,----'|  |_)  |      /  ^  \    |  |__   `---|  |----`
 |  |     |      /      /  /_\  \   |   __|      |  |
 |  `----.|  |\  \----./  _____  \  |  |         |  |
  \______|| _| `._____/__/     \__\ |__|         |__|
 
     A       N   E   W       I   N   S   T   A   L   L
               ______ .___  ___.      _______.
              /      ||   \/   |     /       |
             |  ,----'|  \  /  |    |   (----`
             |  |     |  |\/|  |     \   \
             |  `----.|  |  |  | .----)   |
              \______||__|  |__| |_______/


Generating an application ID ... done (CraftCMS--e8279XXXX)
Generating a security key ... done (UgSm61wTXXXX)

Welcome to Craft CMS!

Are you ready to begin the setup? (yes|no) [no]:
```

### Steps To Reproduce

1. Execute:

```
mkdir craft5-ddev && \ 
  cd craft5-ddev && \
  ddev config \
    --project-type=craftcms \
    --docroot=web \
    --create-docroot \
    --php-version="8.2" \
    --database="mysql:8.0" \
    --nodejs-version="20" && \
  ddev start -y && \
  ddev composer create -y --no-scripts --no-interaction craftcms/craft && \
  ddev craft install/craft \
    --username=admin \
    --password=password123 \
    --email=admin@example.com \
    --site-name=Testsite \
    --language=en \
    --site-url='$DDEV_PRIMARY_URL' && \
  echo 'Nice, ready to launch!' && \
  ddev launch
  ```
  
2. Check the normal composer installation, works with `--no-interaction`:
  
```
ddev ssh
composer create-project craftcms/craft --no-interaction my-craft-project
```

### Anything else?

- CraftCMS related source code:  `@php craft setup/welcome` - ActionWelcome checks for if (!$this->interactive https://github.com/craftcms/cms/blob/5.x/src/console/controllers/SetupController.php#L168 --> and this is set here https://github.com/craftcms/cms/blob/c2f58dce722f79baa208b879f821f74960627a12/src/console/ControllerTrait.php#L171.

```
    protected function checkTty(): void
    {
        // Don't treat this as interactive if it doesn't appear to be a TTY shell
        if ($this->interactive && !Process::isTtySupported()) {
            $this->interactive = false;
        }
    }
 ```
 
So maybe this needs to be changed here in DDEV when `--no-interaction` is passed? 🤔 (just a guess)
https://github.com/ddev/ddev/blob/70fc4cd7b8b84600c18f0435f2ca82f1dba8b730/cmd/ddev/cmd/composer-create.go#L284C36-L284C41
 
 
 ```
 		stdout, stderr, _ = app.Exec(&ddevapp.ExecOpts{
			Service: "web",
			Dir:     app.GetComposerRoot(true, false),
			RawCmd:  composerCmd,
			Tty:     isatty.IsTerminal(os.Stdin.Fd()),
		})
```
 
 Or this https://github.com/ddev/ddev/blob/70fc4cd7b8b84600c18f0435f2ca82f1dba8b730/cmd/ddev/cmd/composer-create.go#L237C4-L244C1
 
 ```
 for _, osarg := range osargs {
				for _, supportedArg := range supportedArgs {
					if strings.HasPrefix(osarg, supportedArg) {
						composerCmd = append(composerCmd, osarg)
					}
				}
			}
```

needs to be appended to the second command to 
``` 
// Try to run post-create-project-cmd.
composerCmd = []string{
```

as well (second guess).

- DDEV improved ddev composer create in v1.23.1 - the post-create-project-cmd is now being executed properly  (https://github.com/ddev/ddev/pull/5058). Wasn't executed before as far as I understand. 
- My guide for previous versions of DDEV: https://dev.to/mandrasch/install-craft-cms-v5-alpha-with-one-command-via-ddev-4ne5)

**Comment by mandrasch** [comment] 2024-05-25 14:09
Tried a quick fix via Gitpod (https://ddev.readthedocs.io/en/stable/developers/building-contributing/#open-in-gitpod) for `cmd/ddev/cmd/composer-create.go`, seemed to work for my use case so far:

```go 
			if !preserveFlags && composerManifest != nil && composerManifest.HasPostCreateProjectCmdScript() {
			
                                 // Try to run post-create-project-cmd.
				composerCmd = []string{
					"composer",
					"run-script",
				}

				// Apply args supported for run-script
				supportedArgs := []string{
					"--dev",
					"--no-dev",
					"-q",
					"--quiet",
					"--ansi",
					"--no-ansi",
					"-n",
					"--no-interaction",
					"--profile",
					"--no-plugins",
					"--no-scripts",
					"-d",
					"--working-dir",
					"--no-cache",
					"-v",
					"-vv",
					"-vvv",
					"--verbose",
				}

				for _, osarg := range osargs {
					for _, supportedArg := range supportedArgs {
						if strings.HasPrefix(osarg, supportedArg) {
							composerCmd = append(composerCmd, osarg)
						}
					}
				}

				composerCmd = append(composerCmd, "post-create-project-cmd")
```

**Comment by stasadev** [comment] 2024-06-13 22:09
@mandrasch, I have a fix for this issue in:

- #6303

**Comment by tyler36** [comment] 2024-06-14 00:02
@mandrasch This looks like the same class of problem I had with CakePHP (#6300) .
I confirmed @stasadev's #6303 fixes it there and I'm betting it will for this too.

**Comment by mandrasch** [comment] 2024-06-14 14:01
@tyler36 thanks for information! 👍 

I just realized that the problem also seemed to be that `--no-scripts` wasn't working properly.

The official craft docs (https://craftcms.com/docs/5.x/install.html#quick-start) do not mention `--no-interaction` at all:

```
ddev composer create -y --no-scripts "craftcms/craft"
```

> --no-scripts: Skips execution of scripts defined in composer.json.

I briefly tested the new awesome PR by Stas and both variants seem to work properly now 🎉 

```
ddev composer create -y --no-scripts "craftcms/craft"
ddev composer create -y --no-interaction "craftcms/craft"
```

**Closed** 2024-06-26 21:39 UTC
