### ISSUE TITLE
sequelace missing from autocomplete

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5344] opened 2023-09-18 09:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /var/folders/t3/ptwnwfr90m93bpx3k3l2d8vw0000gn/T/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project bi-com-careers-fr: [/Users/joachim/Sites/bi-com-sources/bi-com-careers-fr/.ddev/config.yaml]
name: bi-com-careers-fr
type: drupal9
docroot: docroot
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:20230803_php_serialize_precision
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 18
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-15445 in ../tryddevproject-15445 =========
OS Information: Darwin Joachims-iMac.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
ProductName:		macOS
ProductVersion:		13.5.1
BuildVersion:		22G90
User information: uid=501(joachim) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE
 DDEV version     v1.22.1
 architecture     arm64
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0
 docker           23.0.6
 docker-compose   v2.20.0
 docker-platform  colima
 mutagen          0.17.2
 os               darwin
 router           traefik:v2.10
 web              ddev/ddev-webserver:20230803_php_serialize_precision
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=mutagen
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.20.0
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
traefik-monitor-port=10999

======= DOCKER info =========
docker location: lrwxr-xr-x@ 1 joachim  admin  34  3 Sep 10:36 /opt/homebrew/bin/docker -> ../Cellar/docker/24.0.5/bin/docker
Docker Desktop Version: Print: Entry, ":CFBundleShortVersionString", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Docker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plistDocker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plist
docker version:
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.6
 Git commit:        ced0996600
 Built:             Wed Jul 19 19:44:22 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
--------------------------------------------------------------------------------
Name: drupal-core-composer
Identifier: sync_jk0eTpVadJh467urkqEdE4Qr3BTbF8t0xcv84vtiRya
Labels:
	com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
	com.ddev.volume-signature: Users-joachim-colima-default-1693840919
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/drupal-core-composer
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-drupal-core-composer-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
Name: ddev-5318
Identifier: sync_TXu08v3a8vRg941F1jjWtaNbxbgOJhlgsLHD13x9Spc
Labels:
	com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
	com.ddev.volume-signature: Users-joachim-colima-default-1693903776
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/ddev-5318
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-ddev-5318-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
Name: bi-com-refactor
Identifier: sync_k2Gu27ipiyk4JoO2SXWk9G5KbyosXfaczELEkNgylSW
Labels:
	com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
	com.ddev.volume-signature: Users-joachim-colima-default-1693907860
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/bi-com-refactor
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
Beta:
	URL: docker://ddev-bi-com-refactor-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: Connecting to beta
--------------------------------------------------------------------------------
Name: accounts-8
Identifier: sync_Fu8wQd8IPs1g058qLO6puP13ObF7Hn8peQk5BAvlWJL
Labels:
	com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
	com.ddev.volume-signature: Users-joachim-colima-default-1693915721
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/accounts-8
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-accounts-8-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
Name: gws-boehringer-ingelheim-com
Identifier: sync_m6F2hAED5thL9BgJEFJmXiyHDc6i8DB5lm7linaf2Ii
Labels:
	com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
	com.ddev.volume-signature: Users-joachim-colima-default-1693917566
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/bi-com-sources/gws-boehringer-ingelheim-com
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		14029 directories
		58510 files (1.1 GB)
		4 symbolic links
Beta:
	URL: docker://ddev-gws-boehringer-ingelheim-com-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: Yes
	Synchronizable contents:
		14029 directories
		58510 files (1.1 GB)
		4 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: drupal-core-development-project
Identifier: sync_FbCGGdErExLsWegSmTlkX8eHcTitwLEv86LntHXwQeC
Labels:
	com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
	com.ddev.volume-signature: Users-joachim-colima-default-1693927886
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/drupal-core-development-project
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
Beta:
	URL: docker://ddev-drupal-core-development-project-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: Connecting to beta
--------------------------------------------------------------------------------
Name: dcb-development
Identifier: sync_5axcN78TaGzajtP5cwgtJPvDUQ5sc7qjIV4vU9MynJZ
Labels:
	com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
	com.ddev.volume-signature: Users-joachim-colima-default-1694429331
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/web/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/dcb-development
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
Beta:
	URL: docker://ddev-dcb-development-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: Connecting to beta
--------------------------------------------------------------------------------
Name: drupal-core-git
Identifier: sync_OtEPqF4QhAUxhdmVO3FiYkMaTwS1LE1L6yF1x0m4f9D
Labels:
	com.ddev.config-hash: 14ec34369b3ff3ec2757e0868f6d18b23a386b2c
	com.ddev.volume-signature: Users-joachim-colima-default-1694529628
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/drupal-core-git
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
Beta:
	URL: docker://ddev-drupal-core-git-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: Connecting to beta
--------------------------------------------------------------------------------
Name: bi-com-careers
Identifier: sync_r5PeFVzFRj7rRyMVkGLezmT0J7kL9zFVYr1ECkPOwCZ
Labels:
	com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
	com.ddev.volume-signature: Users-joachim-colima-default-1694597375
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/bi-com-sources/bi-com-careers
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		12208 directories
		48526 files (772 MB)
		4 symbolic links
Beta:
	URL: docker://ddev-bi-com-careers-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: Yes
	Synchronizable contents:
		12208 directories
		48526 files (772 MB)
		4 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
Name: bi-com-careers-fr
Identifier: sync_OxdSnKTkwi4swsKO8Fk4CxPqT2hh6fux8vC9mKBbrUU
Labels:
	com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
	com.ddev.volume-signature: Users-joachim-colima-default-1694614861
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/joachim/Sites/bi-com-sources/bi-com-careers-fr
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		11881 directories
		47410 files (502 MB)
		4 symbolic links
Beta:
	URL: docker://ddev-bi-com-careers-fr-web/var/www/html
		DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: Yes
	Synchronizable contents:
		11881 directories
		47410 files (502 MB)
		4 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: colima
Colima version: 0.5.5
Using docker context: default (unix:///Users/joachim/.colima/default/docker.sock)
docker-compose: v2.20.0
Using DOCKER_HOST=unix:///Users/joachim/.colima/default/docker.sock
Docker version: 23.0.6
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  97.9G     15.8G     77.1G  17% /

unable to create project at project root '/Users/joachim/Sites/drupal-core-composer': project root /Users/joachim/Sites/drupal-core-composer does not exist
 Container ddev-accounts-8-web  Stopped
 Container ddev-accounts-8-db  Stopped
 Container ddev-accounts-8-db  Removed
 Container ddev-accounts-8-web  Removed
 Network ddev-accounts-8_default  Removed
Project accounts-8 has been stopped.
 Container ddev-bi-com-careers-db  Stopped
 Container ddev-bi-com-careers-web  Stopped
 Container ddev-bi-com-careers-db  Stopped
 Container ddev-bi-com-careers-web  Stopped
 Container ddev-bi-com-careers-db  Removed
 Container ddev-bi-com-careers-web  Removed
 Network ddev-bi-com-careers_default  Removed
Project bi-com-careers has been stopped.
 Container ddev-bi-com-careers-fr-db  Stopped
 Container ddev-bi-com-careers-fr-web  Stopped
 Container ddev-bi-com-careers-fr-web  Stopped
 Container ddev-bi-com-careers-fr-db  Stopped
 Container ddev-bi-com-careers-fr-db  Removed
 Container ddev-bi-com-careers-fr-web  Removed
 Network ddev-bi-com-careers-fr_default  Removed
Project bi-com-careers-fr has been stopped.
 Container ddev-bi-com-refactor-web  Stopped
 Container ddev-bi-com-refactor-db  Stopped
 Container ddev-bi-com-refactor-db  Removed
 Container ddev-bi-com-refactor-web  Removed
 Network ddev-bi-com-refactor_default  Removed
Project bi-com-refactor has been stopped.
 Container ddev-dcb-development-db  Stopped
 Container ddev-dcb-development-web  Stopped
 Container ddev-dcb-development-db  Removed
 Container ddev-dcb-development-web  Removed
 Network ddev-dcb-development_default  Removed
Project dcb-development has been stopped.
 Container ddev-drupal-core-development-project-web  Stopped
 Container ddev-drupal-core-development-project-db  Stopped
 Container ddev-drupal-core-development-project-db  Removed
 Container ddev-drupal-core-development-project-web  Removed
 Network ddev-drupal-core-development-project_default  Removed
Project drupal-core-development-project has been stopped.
 Container ddev-drupal-core-git-web  Stopped
 Container ddev-drupal-core-git-db  Stopped
 Container ddev-drupal-core-git-db  Removed
 Container ddev-drupal-core-git-web  Removed
 Network ddev-drupal-core-git_default  Removed
Project drupal-core-git has been stopped.
 Container ddev-gws-boehringer-ingelheim-com-db  Stopped
 Container ddev-gws-boehringer-ingelheim-com-web  Stopped
 Container ddev-gws-boehringer-ingelheim-com-db  Stopped
 Container ddev-gws-boehringer-ingelheim-com-web  Stopped
 Container ddev-gws-boehringer-ingelheim-com-db  Removed
 Container ddev-gws-boehringer-ingelheim-com-web  Removed
 Network ddev-gws-boehringer-ingelheim-com_default  Removed
Project gws-boehringer-ingelheim-com has been stopped.
Stopped mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Network ddev_default created
Starting tryddevproject-15445...
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
 Network ddev-tryddevproject-15445_default  Created
 Container ddev-tryddevproject-15445-db  Created
 Container ddev-tryddevproject-15445-web  Created
 Container ddev-tryddevproject-15445-web  Started
 Container ddev-tryddevproject-15445-db  Started
You have Mutagen enabled and your 'php' project type doesn't have `upload_dirs` set.
For faster startup and less disk usage, set upload_dirs to where your user-generated files are stored.
If this is intended you can disable this warning with `ddev config --disable-upload-dirs-warning`.
Starting mutagen sync process... This can take some time.
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st tryddevproject-15445 -l'
 Container ddev-router  Created
 Container ddev-router  Started
Successfully started tryddevproject-15445
Project can be reached at https://tryddevproject-15445.ddev.site https://127.0.0.1:32785
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 18 Sep 2023 09:34:17 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-15445.ddev.site from outside:
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Mon, 18 Sep 2023 09:34:17 GMT
Server: nginx
Vary: Accept-Encoding

======== full curl of http://tryddevproject-15445.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-15445'
======== Project ownership on host:
drwxr-xr-x@ 4 joachim  staff  128 18 Sep 10:33 ../tryddevproject-15445
======== Project ownership in container:
drwxr-xr-x 4 joachim dialout 4096 Sep 18 09:34 /var/www/html
======== In-container filesystem:
Filesystem                     Type 1K-blocks     Used Available Use% Mounted on
/dev/disk/by-label/data-volume ext4 102625208 16499908  80866088  17% /var/www
======== curl again of tryddevproject-15445 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-15445'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds

Please run cleanup after debugging with 'ddev debug testcleanup'
```
</details>         

### Expected Behavior

There is no autocomplete for the sequelace command

### Actual Behavior

I only get 'ddev service'.

### Steps To Reproduce

1. Type `ddev se<TAB>`

**Comment by rfay** [comment] 2023-09-18 12:54
sequelace and any other things that are dependent on something being installed. (So all the database browsers for example, like tableplus, etc.). 

During the creation of the autocomplete stuff, which is done on Linux, sequelace isn't there. 

Also, things like `ddev drush` aren't there because they're project-specific, so aren't created for the same reason. 

I'm not sure what the right thing is to do for all of these. 

I imagine this is a duplicate of
* https://github.com/ddev/ddev/issues/2961

Related:
* https://github.com/ddev/ddev/issues/3085
* https://github.com/ddev/ddev/issues/4880

**Comment by rfay** [comment] 2023-09-23 20:16
I don't see dealing with this directly but the other issues cover it. It would be great for everything to show.. when it should. But of course we don't want people on linux getting sequelace completions. Closing for now as duplicate, happy to continue the conversation here or elsewhere.

**Closed by rfay** 2023-09-23 20:16 UTC
