### ISSUE TITLE
Unexpected db_dump value on 1.22.6 with newer Acquia CLI versions

### ISSUE THREAD

**Issue by rcaldeiradev** [ddev/ddev#5697] opened 2024-01-15 22:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[32mRunning bash [-c /var/folders/s5/v6b9whxd4bq7cmbz1trkbzdc0000gn/T/test_ddev.sh][0m
======= Existing project config =========
These config files were loaded for project site: [/Users/rafael/projects/bridge/company/site/.ddev/config.yaml]
name: site
type: drupal10
docroot: docroot
php_version: 8.1
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-30881 in ../tryddevproject-30881 =========
OS Information: Darwin Rafaels-MBP 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
User information: uid=501(rafael) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.5                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5             
 docker           20.10.12                                
 docker-compose   v2.16.0                                 
 docker-platform  docker-desktop                          
 mutagen          0.16.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.21.5                
 web              drud/ddev-webserver:v1.21.5             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: lrwxr-xr-x  1 root  wheel  54 Mar  7  2022 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.5.0 build 74594
docker version: 
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
--------------------------------------------------------------------------------
Name: site
Identifier: sync_rjRFd5hvDSbWDC0qwnxUCv7K8XNt2mYxeQWqIQvNl3Y
Labels:
	com.ddev.config-hash: 654a7799e053320033f4baa45c0f9c345f2546e4
	com.ddev.volume-signature: var-run-1705352025
Configuration:
	Synchronization mode: Two Way Resolved
	Hashing algorithm: Default (SHA-1)
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/sites/default/files
	Permissions mode: Default (Portable)
Alpha:
	URL: /Users/rafael/projects/bridge/company/site
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-site-web/var/www/html
		DOCKER_HOST=unix:///var/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
		Compression: Default (DEFLATE)
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
======= Docker Info =========
[32mDocker platform: docker-desktop[0m
[32mUsing docker context: default (unix:///var/run/docker.sock)[0m
[32mdocker-compose: v2.16.0[0m
[32mUsing DOCKER_HOST=unix:///var/run/docker.sock[0m
[32mDocker version: 20.10.12[0m
[32mAble to run simple container that mounts a volume.[0m
[32mAble to use internet inside container.[0m
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 149.4G     68.5G     73.3G  48% /

 Container ddev-site-web  Stopped
 Container ddev-site-dba  Stopped
 Container ddev-site-db  Stopped
 Container ddev-site-web  Stopped
 Container ddev-site-db  Stopped
 Container ddev-site-dba  Stopped
 Container ddev-site-dba  Removed
 Container ddev-site-db  Removed
 Container ddev-site-web  Removed
 Network ddev-site_default  Removed
[32mProject site has been stopped.[0m
[32mStopped mutagen daemon[0m
Existing docker containers: 
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                      PORTS                                                  NAMES
63d69aa1282b   xhprof_web                      "docker-php-entrypoi…"   4 months ago    Exited (255) 4 months ago   0.0.0.0:80->80/tcp                                     web
2d3fd824a077   schickling/mailcatcher          "sh -c 'mailcatcher …"   4 months ago    Exited (255) 4 months ago   127.0.0.1:55005->1025/tcp, 127.0.0.1:55004->1080/tcp   sinfonia_mailer_1
ac0d99c72a55   blackfire/blackfire:2           "/usr/local/bin/entr…"   4 months ago    Exited (1) 4 months ago                                                            sinfonia_blackfire_1
3d9ab964732e   postgres:15-alpine              "docker-entrypoint.s…"   4 months ago    Exited (255) 4 months ago   127.0.0.1:55006->5432/tcp                              sinfonia_database_1
32d1a8d7374f   drud/ddev-webserver:v1.19.0-1   "sh -c 'chown -R 501…"   12 months ago   Exited (0) 12 months ago                                                           dreamy_mendel
7dd735b3e914   drud/ddev-webserver:v1.19.0-1   "sh -c 'chown -R 501…"   13 months ago   Exited (0) 13 months ago                                                           silly_johnson
872c8df8749c   sail-8.1/app                    "start-container"        14 months ago   Exited (0) 14 months ago                                                           builder-laravel.test-1
8d43dcadabaa   mysql/mysql-server:8.0          "/entrypoint.sh mysq…"   14 months ago   Exited (0) 14 months ago                                                           builder-mysql-1
f016a69e180d   drud/ddev-webserver:v1.19.0-1   "sh -c 'df / | awk '…"   21 months ago   Exited (0) 21 months ago                                                           adoring_franklin
[32mCreating a new ddev project config in the current directory (/Users/rafael/projects/bridge/company/tryddevproject-30881)[0m
[32mOnce completed, your configuration will be written to /Users/rafael/projects/bridge/company/tryddevproject-30881/.ddev/config.yaml
[0m
[32mConfiguring unrecognized codebase as project type 'php' at /Users/rafael/projects/bridge/company/tryddevproject-30881/web[0m
[32mConfiguration complete. You may now run 'ddev start'.[0m
Network ddev_default created
Starting tryddevproject-30881...
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
 Network ddev-tryddevproject-30881_default  Created
 Container ddev-tryddevproject-30881-dba  Created
 Container ddev-tryddevproject-30881-db  Created
 Container ddev-tryddevproject-30881-web  Created
 Container ddev-tryddevproject-30881-dba  Started
 Container ddev-tryddevproject-30881-db  Started
 Container ddev-tryddevproject-30881-web  Started
 Container ddev-router  Created
 Container ddev-router  Started
[32mSuccessfully started tryddevproject-30881[0m
[32mProject can be reached at https://tryddevproject-30881.ddev.site https://127.0.0.1:61899[0m
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Jan 2024 21:48:19 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-30881.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 15 Jan 2024 21:48:19 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-30881.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-30881'
======== Project ownership on host:
drwxr-xr-x  4 rafael  staff  128 Jan 15 18:47 ../tryddevproject-30881
======== Project ownership in container:
drwxr-xr-x 4 rafael dialout 128 Jan 15 21:47 /var/www/html
======== In-container filesystem:
Filesystem     Type          1K-blocks      Used Available Use% Mounted on
grpcfuse       fuse.grpcfuse 482797652 376233748 106563904  78% /var/www/html
======== curl again of tryddevproject-30881 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-30881'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-30881'

```
</details>         

### Expected Behavior

Run `ddev pull acquia`, it should: 
- Download a database backup and import it
- Download projects' files 

### Actual Behavior

The "cp" command fails:

```
/Users/rafael/projects/bridge/company/site [main]% ddev pull acquia
You're about to delete the current database and files and replace with the results of a fresh pull.
Would you like to continue? [Y/n] (yes):
Authenticating...
Acquia CLI 2.21.1 is available. Run acli self-update to update.
The following Cloud Platform API key is active: PersonalSaved credentials
Obtaining databases...
Using ACQUIA_ENVIRONMENT_ID=site.dev
++ tail -2l
++ acli pull:db site.dev --no-interaction --no-import
++ xargs
+ db_dump='[OK] site database backup downloaded to /tmp/dev-site-sitedev-2024-01-15T06:08:45+00:00.sql.gz'
+ ls /var/www/html/.ddev
+ cp '[OK]' site database backup downloaded to /tmp/dev-site-sitedev-2024-01-15T06:08:45+00:00.sql.gz /var/www/html/.ddev/.downloads/db.sql.gz
cp: target '/var/www/html/.ddev/.downloads/db.sql.gz' is not a directory
Pull failed: failed to exec set -eu -o pipefail
# xargs here just trims whitespace
# We could use an easier technique when https://github.com/acquia/cli/issues/1629 is resolved
# just using `acli pull:db ${ACQUIA_ENVIRONMENT_ID}`
echo "Using ACQUIA_ENVIRONMENT_ID=${ACQUIA_ENVIRONMENT_ID}"
set -x   # You can enable bash debugging output by uncommenting
db_dump=$(acli pull:db ${ACQUIA_ENVIRONMENT_ID} --no-interaction --no-import | tail -2l | xargs)
ls /var/www/html/.ddev >/dev/null # This just refreshes stale NFS if possible
cp ${db_dump} /var/www/html/.ddev/.downloads/db.sql.gz
 on web: exit status 1
```

### Steps To Reproduce

1. Make sure you're running ddev v1.22.6
2. Setup the Acquia Integration https://ddev.readthedocs.io/en/latest/users/providers/acquia/
3. Run `ddev pull acquia`. You should see a database copy error.

### Anything else?

After analyzing the code in the `db_pull_command` script present in the `.ddev/providers/acquia.yaml` file, I noticed that it attempts to retrieve the last two lines of the `acli pull:db` command's output:

```
db_pull_command:
  command: |
    [...]
    db_dump=$(acli pull:db ${ACQUIA_ENVIRONMENT_ID} --no-interaction --no-import | tail -2l | xargs)
    [...]
```

However, on DDEV v1.22.6, which runs a newer version of Acquia CLI (2.21.1), the `pull:db` command returns the message `"[OK] site database backup downloaded to[...]"` without a line break before the file name:

```rafael@site-web:/var/www/html$ acli pull:db site.dev --no-import --no-interaction
 [INFO] Using a database backup that is 15 hours old. Backup #271980282 was created at Mon Jan 15 6:08:45 UTC 2024.

        You can view your backups here: https://cloud.acquia.com/a/environments/144810-191bfd80-6de2-4ef0-855c-b8e2211f3301/databases

        To generate a new backup, re-run this command with the --on-demand option.


    ✔ Downloading site database copy from the Cloud Platform

 [OK] site database backup downloaded to /tmp/dev-site-sitedev-2024-01-15T06:08:45+00:00.sql.gz
```

On DDEV v1.22.5, which uses an older version of Acquia CLI (2.8.1.0), the acli pull:db command returns a line break after the message `"[OK] site database backup downloaded to[...]"`, before the file name:
```
rafael@site-web:/var/www/html$ acli pull:db site.dev --no-import --no-interaction
Acquia CLI 2.21.1 is available. Run acli self-update to update.


 [INFO] Using a database backup that is 15 hours old. Backup #271980282 was created at Mon Jan 15 6:08:45 UTC 2024.

        You can view your backups here:
        https://cloud.acquia.com/a/environments/144810-191bfd80-6de2-4ef0-855c-b8e2211f3301/databases

        To generate a new backup, re-run this command with the --on-demand option.


    ✔ Downloading site database copy from the Cloud Platform

 [OK] site database backup downloaded to
      /tmp/dev-site-eb01cce17daf40f281b27f81abd6557a-2024-01-15T06:08:45+00:00.sql.gz
```

Ideally, there should be a way to make Acquia CLI return only the downloaded file name with `acli pull:db`. Otherwise, implementing a regex to extract the file name along with the path could enhance the reliability of that script.

**Comment by rfay** [comment] 2024-01-16 00:16
Hi @rcaldeiradev - Are you sure you haven't altered the acquia.yaml? We have automated tests that are completing successfully on `ddev pull acquia`. 

* https://github.com/acquia/cli/issues/1629  was actually resolved after discussions related to this implementation, and the approach described there would resolve your issue. Would you like to try it out and create a PR?

Alternately ,maybe you'd be interested in just solving the newline problem that you've analyzed?

**Comment by rcaldeiradev** [comment] 2024-01-17 15:50
Hi @rfay . 

Yeah, no changes were made to acquia.yaml.
Will do soon. I'll also check the tests. 

Thanks!

**Comment by rfay** [comment] 2024-01-19 01:13
Our automated tests are running fine against Acquia. I'll try to set up a manual pull tomorrow and verify, but at this point it looks like to could be something "special" about your project.

**Comment by rfay** [comment] 2024-01-19 13:39
I am able to reproduce your results. Could you please either try the DDEV binary provided in this PR or use the acquia.yaml file from https://github.com/ddev/ddev/blob/538ec3bcff3e6af7bf1274b3e8a48119ff4089bf/pkg/ddevapp/dotddev_assets/providers/acquia.yaml (but you have to remove the #ddev-generated from the top of it)

Should be fixed in
* #5714

**Comment by rcaldeiradev** [comment] 2024-01-22 14:45
Hi @rfay ,

I've tested the acquia.yaml file you provided, and it worked fine.

Thanks!

**Closed** 2024-01-26 19:54 UTC
