### ISSUE TITLE
ddev stop --unlist failed with invalid hostname error

### ISSUE THREAD

**Issue by julienloizelet** [ddev/ddev#5818] opened 2024-02-11 01:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

https://gist.github.com/julienloizelet/d513130b508909c385997edd1e366ac7
</details>         

### Expected Behavior

When I run `ddev stop --unlist test-hostname`, it should unlist the project.

### Actual Behavior

When I run `ddev stop --unlist <some-project>`, I have the error:

```
Failed to get project(s): the  project has an invalid hostname: 'test-hostname.', see https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements
```

### Steps To Reproduce

1. create a project : `ddev config --project-type=php --project-name=test-hostname`
2. ddev start
3. ddev stop
4. Manually change the name of the project in the config.yaml file: set test-hostname-new for example
5. ddev restart

=> there will be an expected error message like: 
```
Failed to restart test-hostname-new: this project root /home/julien/workspace/test/test-ddev already contains a project named test-hostname. You may want to remove the existing project with "ddev stop --unlist test-hostname" 
```

6. Run ddev stop --unlist test-hostname => unexpected error appears
```
Failed to get project(s): the  project has an invalid hostname: 'test-hostname.', see https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements
```

(I have to manually delete the entry in the ddev global_config.yaml to make it work)

**Comment by rfay** [comment] 2024-02-11 02:06
Your project seems to have the name `test-hostname.` with a dot on the end? Which is invalid. But you should have been prevented from creating it I'd think.

**Comment by julienloizelet** [comment] 2024-02-11 02:43
> Your project seems to have the name `test-hostname.` with a dot on the end? Which is invalid. But you should have been prevented from creating it I'd think.

There is no dot at the end of my project name.
I've run `ddev config --project-type=php --project-name=test-hostname` and double-checked in the created `config.yaml` file

**Comment by rfay** [comment] 2024-02-11 03:21
Would you mind sharing your ~/.ddev/global_config.yaml ? Take a look and see if there's anything sensitive in it, remove the comments at the bottom. You can share as a gist, or PM if you want in Discord or whatever. Thanks!

**Comment by rfay** [comment] 2024-02-11 03:22
BTW, if your only goal is actually to unlist, just remove the stanza from your global_config.yaml.

**Comment by julienloizelet** [comment] 2024-02-11 03:44
> BTW, if your only goal is actually to unlist, just remove the stanza from your global_config.yaml.

Yes, i'm doing this for the moment :)

**Comment by rfay** [comment] 2024-02-11 04:26
Thanks for sharing your global_config.yaml. 

I'm unable to reproduce your situation. 

```
rfay@rfay-tag1-m1 test-hostname % ddev config --auto
You are reconfiguring the project at /Users/rfay/workspace/test-hostname.
The existing configuration will be updated and replaced.
Configuring a 'php' project with docroot '' at /Users/rfay/workspace/test-hostname
Configuration complete. You may now run 'ddev start'.
rfay@rfay-tag1-m1 test-hostname % ddev stop --unlist test-hostname
Project test-hostname is already stopped.
Project test-hostname has been stopped.
rfay@rfay-tag1-m1 test-hostname % ddev start
You seem to have a new DDEV version.
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes): no
Starting test-hostname...
Network ddev-test-hostname_default created
Building project images...
Project images built in 1s.
 Container ddev-test-hostname-web  Created
 Container ddev-test-hostname-db  Created
 Container ddev-test-hostname-db  Started
 Container ddev-test-hostname-web  Started
You have Mutagen enabled and your 'php' project type doesn't have `upload_dirs` set.
For faster startup and less disk usage, set upload_dirs to where your user-generated files are stored.
If this is intended you can disable this warning with `ddev config --disable-upload-dirs-warning`.
Starting Mutagen sync process...
Mutagen sync flush completed in 2s.
For details on sync status 'ddev mutagen st test-hostname -l'
Waiting for web/db containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Running
Waiting for additional project containers to become ready...
All project containers are now ready.
Successfully started test-hostname
Project can be reached at https://test-hostname.ddev.site https://127.0.0.1:32945
rfay@rfay-tag1-m1 test-hostname % ddev stop --unlist test-hostname
 Container ddev-test-hostname-db  Stopped
 Container ddev-test-hostname-web  Stopped
 Container ddev-test-hostname-web  Stopped
 Container ddev-test-hostname-db  Stopped
 Container ddev-test-hostname-db  Removed
 Container ddev-test-hostname-web  Removed
 Network ddev-test-hostname_default  Removed
Project test-hostname has been stopped.
rfay@rfay-tag1-m1 test-hostname %
```

Can you see if you can recreate it by removing the various stanzas from your global_config.yaml and then trying to reproduce?

**Comment by julienloizelet** [comment] 2024-02-11 05:50
I can't see in your test where you are changing the project name from "test-hostname" to "test-hostname-new" (as in my 4th step to reproduce) ?

BTW, I removed all the stanzas and I still have the issue.

FYI, I also add this error on another machine (a Mac M2 with other projects). And it happens with all tested project names.

Here is my last test: 

```
pwd
/home/julien/workspace/test/test-ddev/test-hostname
❯ ddev start
Starting test-hostname... 
Network ddev-test-hostname_default created 
Building project images... 
Project images built in 0s. 
 Container ddev-test-hostname-web  Created 
 Container ddev-test-hostname-db  Created 
 Container ddev-test-hostname-web  Started 
 Container ddev-test-hostname-db  Started 
Waiting for web/db containers to become ready: [web db] 
Starting ddev-router if necessary... 
 Container ddev-router  Created 
 Container ddev-router  Started 
Waiting for additional project containers to become ready... 
All project containers are now ready. 
Successfully started test-hostname 
Project can be reached at https://test-hostname.ddev.site https://127.0.0.1:32775 
❯ ddev stop
 Container ddev-test-hostname-db  Stopped 
 Container ddev-test-hostname-web  Stopped 
 Container ddev-test-hostname-db  Stopped 
 Container ddev-test-hostname-web  Stopped 
 Container ddev-test-hostname-db  Removed 
 Container ddev-test-hostname-web  Removed 
 Network ddev-test-hostname_default  Removed 
Project test-hostname has been stopped. 
❯ sed -i -e 's/test-hostname/test-hostname-new/g' .ddev/config.yaml
❯ ddev start
Starting test-hostname-new... 
Network ddev-test-hostname-new_default created 
Failed to start test-hostname-new: this project root /home/julien/workspace/test/test-ddev/test-hostname already contains a project named test-hostname. You may want to remove the existing project with "ddev stop --unlist test-hostname" 
❯ ddev stop --unlist test-hostname
Failed to get project(s): the test-hostname project has an invalid hostname: 'test-hostname.', see https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements


```

**Comment by rfay** [comment] 2024-02-11 14:42
I'm sorry, I didn't read your repro carefully enough. 

The way to change the name of a project is given in the FAQ, https://ddev.readthedocs.io/en/latest/users/usage/faq/#workflow

I think if you do that you'll be OK.

I am able to find my way to the error you describe; however, if I use `ddev config --project-name` instead of manually editing it catches the problem and prevents it. 

I guess since there is a valid, documented way to change the name of a project, and since it takes a lot of work to get this, I don't think I want to chase it, so I'm going to close it. Happy to continue the conversation here or elsewhere, and happy to reconsider if you think it's important.

**Closed by rfay** 2024-02-11 14:42 UTC

**Comment by julienloizelet** [comment] 2024-02-13 00:10
Thanks for the `ddev config --project-name` hint. I didn't know about this method :)
I agree that I should use this documented method to change the name instead of manually editing the file.

**Comment by ariademur** [comment] 2024-04-11 10:13
I've also edited the project name manually and had exactly the same error.

In order to solve it, I had to delete the project entry from both `global_config.yaml` and `project_list.yaml`.

Hopefully this helps someone save some time.
