### ISSUE TITLE
React, NextJS, Angular or other JS projects with own server

### ISSUE THREAD

**Issue by macmladen** [ddev/ddev#4898] opened 2023-05-11 08:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

All those frameworks provide their own server with options to `build` and `start` or to use `dev` which includes **watch**. After that, we go to `localhost:3000` and test from there.

What I would like is to issue `ddev config` which can recognise React/NextJS/Angular/etc type of project, preconfigure containers and router and serve the web site on **myreact.ddev.site**

### Describe your solution

There may be two approaches:

1. One that excludes the **web** container and uses some app to serve like `npm run dev` which is then exposed as the projects entry point for the domain, i.e the **npm** port 3000 (or any other) is exposed as 80 by the router, removing the need for the port.

2. The other, where the **nginx** is used to listen to port 3000 and expose it to the world as the port 80

### Describe alternatives

It would be even greater if we could use additional FQDN which could be tied to ports.

I.e. we may have a NextJS web app (tested as **build** and as **dev**), backed in PHP (API), some JS service and other stuff like some db, phpMyAdmin, MailHog, etc.

The proposition would be to be able to assign an arbitrary port to FQDN, e.g.

```
(tech)   container: port FQDN
---------------------------------------
(nextjs)     build: 3000:80   mynext.ddev.site
(nextjs)       dev: 3001:80   dev.mynext.ddev.site
(PHP)          api:   80:80   api.mynext.ddev.site
(nodejs)   service: 3002:80   service.mynext.ddev.site
(PHP)           db: 3306:3306 mynext.ddev.site
(PHP)          dba:   80:80   dba.mynext.ddev.site
(MailHog)      hog: 1025:80   hog.mynext.ddev.site
```

### Additional context

The idea is to mimic the real-world setup as closely as possible.

It also opens the possibility to use/expose more services by domain. Instead of hacking my way through `nginx.conf` and/or port exposing/assigning, if this is not too complicated it could lower the tech skill needed to have that up and going.

Also, there are many developers now using various JS tech stacks who can benefit from such a local environment and be able to add other services like different db's and to exlopre.

**Comment by tyler36** [comment] 2023-05-11 08:28
Duplicate of #4854  ?

**Comment by macmladen** [comment] 2023-05-11 08:47
Haven't found that one, I was looking for 'React'.

This issue extends to the idea that services **ports** can be mapped to FQDN and also enable exposing the service port (3000) to the custom domain port, 80 or any other.

I'd also like the option to recognise some of the most popular frameworks React/Angular/Vue/NextJS and be open to adding more to remove the traction from easily starting the JS project with **ddev**.

**Comment by tyler36** [comment] 2023-05-11 08:57
> I'd also like the option to recognise some of the most popular frameworks React/Angular/Vue/NextJS and be open to adding more to remove the traction from easily starting the JS project with ddev.

#4854 is the place to "vote" for you prefered framework and what port it prefers. 

There's also the option of creating an addon that might solve your immediate use case. The below addons both expose ports used by javascript.

- https://github.com/ddev/ddev-browsersync
- https://github.com/torenware/ddev-viteserve

**Comment by macmladen** [comment] 2023-05-11 09:26
@tyler36 Thanks, these may deserve mentioning in the docs as they are quite valuable. You gave me some ideas about how can I solve it and I agree that the rest should be discussed there.

The part with the FQDN and ports still make sense and is new idea/feature request here?

**Comment by rfay** [comment] 2023-05-11 15:03
@macmladen there are so many different ways to use these projects. 

I do think that 
* #4854 

is probably the essence of what you're looking for (using nginx as a front-end for a server-side JS platform like node?)

But if you're looking for front-end things there's nothing actually to be done.

As @tyler36 points out, DDEV already has capabilities that are along the line you're looking for, see https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#using-nodejs-with-ddev - the `web_extra_daemons` and `web_extra_exposed_ports` do all the things; the only problem is if you don't want the result exposed on a non-standard port.

**Comment by rfay** [comment] 2023-05-17 17:07
No response to conversation, and https://github.com/ddev/ddev/issues/4854 may be what's desired here. @macmladen if you want to solve a specific problem we can go ahead and discuss that more. You're invited to Discord as well, https://discord.gg/hCZFfAMc5k

**Closed by rfay** 2023-05-17 17:07 UTC
