### ISSUE TITLE
Upgrade failing due to Blackfire "payment required" error

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6235] opened 2024-05-23 07:27 UTC
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

@iainsaxon  reported that they are having troubles upgrading DDEV. #https://github.com/ddev/ddev/issues/5620

> This has become an issue again when I ddev start or ddev d refresh a project:
> 

Also seen in Discord: https://discord.com/channels/664580571770388500/1243100859756183612/1243100859756183612

Starting this issue to track it but have done no research yet (ticked boxes are meaningless).

### Expected Behavior

Upgrade possible

### Actual Behavior

```
1.674 Get:18 http://nginx.org/packages/debian bookworm/nginx arm64 Packages [7973 B]
1.811 Err:19 http://packages.blackfire.io/debian any InRelease
1.811   402  Payment Required [IP: 79.125.77.192 80]
2.089 Get:20 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [123 kB]
```

**Comment by tyler36** [comment] 2024-05-23 08:00
Could someone a complete copy of the debug log?
It will be helpful for debugging. 😄

**Comment by andrewbelcher** [comment] 2024-05-23 08:24
I believe the issue is only when you have custom packages to install - the `apt-get update` fails as the repo endpoint returns a 402. Here's an example from a project I've tried to start:
```
#16 [web 7/8] RUN apt-get update -y &&     apt-get install -y --no-install-recommends --no-install-suggests poppler-utils
#16 0.330 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#16 0.345 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#16 0.345 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#16 0.352 Get:4 http://nginx.org/packages/debian bookworm InRelease [2860 B]
#16 0.383 Get:5 https://packages.sury.org/php bookworm InRelease [7542 B]
#16 0.403 Get:6 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
#16 0.420 Get:7 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#16 0.457 Get:8 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
#16 0.560 Get:9 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
#16 0.651 Get:10 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [156 kB]
#16 0.750 Get:11 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [7975 B]
#16 0.822 Get:12 https://packages.sury.org/php bookworm/main amd64 Packages [229 kB]
#16 0.858 Err:13 http://packages.blackfire.io/debian any InRelease
#16 0.858   402  Payment Required [IP: 54.194.247.67 80]
#16 0.907 Get:14 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [7455 B]
#16 1.074 Get:15 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [6917 B]
#16 2.172 Reading package lists...
#16 3.027 E: Failed to fetch http://packages.blackfire.io/debian/dists/any/InRelease  402  Payment Required [IP: 54.194.247.67 80]
#16 3.027 E: The repository 'http://packages.blackfire.io/debian any InRelease' is not signed.
#16 ERROR: process "/bin/bash -c apt-get update -y &&     apt-get install -y --no-install-recommends --no-install-suggests poppler-utils" did not complete successfully: exit code: 100
------
 > [web 7/8] RUN apt-get update -y &&     apt-get install -y --no-install-recommends --no-install-suggests poppler-utils:
0.651 Get:10 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [156 kB]
0.750 Get:11 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [7975 B]
0.822 Get:12 https://packages.sury.org/php bookworm/main amd64 Packages [229 kB]
0.858 Err:13 http://packages.blackfire.io/debian any InRelease
0.858   402  Payment Required [IP: 54.194.247.67 80]
0.907 Get:14 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [7455 B]
1.074 Get:15 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [6917 B]

3.027 E: Failed to fetch http://packages.blackfire.io/debian/dists/any/InRelease  402  Payment Required [IP: 54.194.247.67 80]
3.027 E: The repository 'http://packages.blackfire.io/debian any InRelease' is not signed.
------
', stderr='failed to solve: process "/bin/bash -c apt-get update -y &&     apt-get install -y --no-install-recommends --no-install-suggests poppler-utils" did not complete successfully: exit code: 100' 
```

**Comment by andrewbelcher** [comment] 2024-05-23 08:27
As a workaround, you can use a `.ddev/web-build/Dockerfile` to install your package _after_ removing the blackfire repo:

```
RUN rm /etc/apt/sources.list.d/blackfire.list && apt-get update -y && \
    apt-get install -y --no-install-recommends --no-install-suggests poppler-utils
```

**Comment by stasadev** [comment] 2024-05-23 08:30
Hi everyone,

You need to update your custom Dockerfiles in these locations:

- `.ddev/web-build/Dockerfile`
- `.ddev/web-build/Dockerfile.*`
- `.ddev/db-build/Dockerfile`
- `.ddev/db-build/Dockerfile.*`

Replace
- `apt-get update` with `(apt-get update || true)`
- `apt update` with `(apt update || true)`

And restart the project.

DDEV can't fix this on our end (until the blackfire.io folks fix it) because these are Dockerfile custom user instructions.

**Comment by stasadev** [comment] 2024-05-23 08:33
> install your package after removing the blackfire repo

Thank you for investigating this @andrewbelcher, this issue seems to be related to our pin for blackfire.io repo:

- #6079

**Comment by webseppel** [comment] 2024-05-23 09:08
It seems to work again! :)

**Comment by thomasdiluccio** [comment] 2024-05-23 13:04
I can confirm from the Blackfire side that the issue is now resolved.

**Comment by rfay** [comment] 2024-05-23 13:19
Closing as this exact problem is fixed upstream, but #6236 will make things more robust in the future. Thanks @stasadev for fixing the various add-ons.

**Closed by rfay** 2024-05-23 13:19 UTC

**Comment by rfay** [comment] 2024-05-23 13:30
Thanks so much for the immediate responsiveness to this @tyler36 !
