### ISSUE TITLE
ZSH completions not working in homebrew (name should be _zsh)

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#5803] opened 2024-02-08 03:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

With ZSH 5.9 with MacOS Sonoma 14.3 and the following line `autoload -Uz compinit && compinit` added to the `.zshrc`file I would expect that autocompletion is working out of the box (without the need of installing Oh-My-ZSH) .

### Actual Behavior

The standard completions work on my system. For example: 
![Screenshot 2024-02-08 at 02 57 07](https://github.com/ddev/ddev/assets/1665422/562ff88a-55bd-43ac-888d-82a45be24db4)
But if I try the same with something like for example `ddev composer <tab>`added in https://github.com/ddev/ddev/pull/5756 nothing happens at all. 

I've done some digging. The "official" location for completion functions is `/usr/share/zsh/5.9/functions` but there is nothing related to DDEV available there. The shell script with the completions is located in `/opt/homebrew/Cellar/ddev/HEAD-5c7cd2b/share/zsh/site-function`. One detail I've noted  is that the filename isn't starting with an underscore according to the naming convention recommended in https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Autoloaded-files - and all completions in `/usr/share/zsh/5.9/functions` start with an underscore as well. @rfay dug up two issues in regards of the name change https://github.com/ddev/ddev/pull/4179 and https://github.com/ddev/ddev/blob/2f4b0551d4f3f36ec2a6fe26b7a7209f6f2b4009/.goreleaser.yml#L224-L239 . But that isn't probably the reason why the completion for DDEV isn't added to the index. The location of the  DDEV zsh completion is probably just unavailable/unknown to `compinit` I suppose. There might be the option of "hardlinking" the completion file as a special directory as outlined here: https://stackoverflow.com/a/61383123 but that wouldn't be very elegant nor flexible (on every update that link would have to be updated).  Guy Sartorelli mentioned over in https://github.com/ddev/ddev/pull/5756 that he is using the completion in zsh in combination with oh-my-zsh and everything is working out of the box? 

One direct question to @GuySartorelli: Has oh-my-zsh added anything in relation to the know completion directories that make zsh autodiscover the completions available for DDEV? Or have you pointed zsh to the ddev cellar?

### Steps To Reproduce

1. Add `autoload -Uz compinit && compinit` to `~/.zshrc`

**Comment by GuySartorelli** [comment] 2024-02-08 03:24
This is at least thematically related to https://github.com/ddev/ddev/issues/5734

> Guy Sartorelli mentioned over in https://github.com/ddev/ddev/pull/5756 that he is using the completion in zsh in combination with oh-my-zsh and everything is working out of the box?

To the best of my knowledge I never performed any setup to get completion running - though it is possible that I did so when I initially set up DDEV and have since forgotten.
My "out of the box" comment on that PR was intended to mean "users who already have completion working with DDEV generally won't need to perform any additional steps to get completion working for the composer commands", not that no setup was required for getting completion to work for DDEV in general.

> Has oh-my-zsh added anything in relation to the know completion directories that make zsh autodiscover the completions available for DDEV?

No idea, but I doubt it has anything _specific_ to DDEV.

> Or have you pointed zsh to the ddev cellar?

I don't know what a cellar is in this context so almost certainly not.

**Comment by rpkoller** [comment] 2024-02-08 12:44
> My "out of the box" comment on that PR was intended to mean "users who already have completion working with DDEV in general won't need to perform any additional steps to get completion working for the composer commands", not that no setup was required for getting completion to work for DDEV in general.
ah i've misunderstood that. thanks for clarification! 

> I don't know what a cellar is in this context so almost certainly not.
that is the location where a homebrew formula is stored. for ddev that is `/opt/homebrew/Cellar/ddev`

I did some more digging and after some sleep my thinking functioned a bit better again ;) and that brought me to the question " how zsh completions from homebrew formulas are made available to zsh in macos" that brought me to two formulas i already knew but never visited their project pages on formulae.brew.sh

https://formulae.brew.sh/formula/zsh-autocomplete
https://formulae.brew.sh/formula/zsh-completions

and turns out both are setting the FPATH making the completions available. now i finally had something more specific to search for and it turns out in the brew docs there are actual instructions in regards of properly setting up completions in zsh: 
https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh

I've followed the lead and added the conditional at the top of my `.zshrc`file 

```
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
```
(but not sure if it is necessary to run compinit another time outside of the if statement)  

and also ran `chmod -R go-w "$(brew --prefix)/share"`since `compaudit`raised a security concern for the general share directory of homebrew

```
$> compaudit
There are insecure directories:
/opt/homebrew/share
```

and also rebuild `zcompdump`with `rm -f ~/.zcompdump; compinit`but ddev wasnt added to that dump after running the rm. so how things work and have to be set up is a lot clearer. the out of the box completions still work but the bespoke ddev ones are not working nor being imported it seems like. still not sure if it necessary to change the completion file name from `ddev`to `_ddev`to be in line with the aforementioned naming conventions for autoload files. but i've manually changed the name, rebuild the dump and tried but same effect still not working. probably still missing one important detail to get things working.

**Comment by rpkoller** [comment] 2024-02-08 15:13
from my perspective it is definitely related. even though the issue is about trying to get autocompletion working already without oh my zsh(omz), omz just takes care of one or two configuration steps for the user. in general it is the same problem no matter if things dont work with or without omz. 

from my point of view what i am trying to figure out in this issue is if there are any installation flaws (i was only looking from a homebrew perspective) and what additional steps are necessary to setup the compeltion for zsh on in particular macos. in regards of installation the only potential problem might be the naming (missing the recommended underscore) but i doubt that that is the reason aside that i am unable to spot anything from the ddev side that could be improved at the moment. it is probably caused some missing or faulty configuration in the .zshrc file. and that is what i am currently focusing on with the endgoal to get it working as well as trying to improve the docs based on those findings. 

out of curiosity @jonsimonsen if you take a look into `~/.zcompdump` do you find anything in relation with ddev? and if not have you tried wiping that dump with `rm -f ~/.zcompdump; compinit`and then rechecked if something ddev related got added after the rebuild of the dump?

**Comment by rpkoller** [comment] 2024-02-08 16:24
oh i misread the propose resolution in https://github.com/ddev/ddev/pull/4179 . thought it was recommended to switch to `ddev` FROM `_ddev`. But yep then 100% agree that this should be fixed in the go releaser for zsh. probably not the reason but still ddev should follow the naming conventions. and yep i will continue tonight to further explore the problem.

**Comment by jonsimonsen** [comment] 2024-02-09 06:43
> out of curiosity @jonsimonsen if you take a look into `~/.zcompdump` do you find anything in relation with ddev? and if not have you tried wiping that dump with `rm -f ~/.zcompdump; compinit`and then rechecked if something ddev related got added after the rebuild of the dump?

I searched for ddev in the file before and after running that command, and did not find it

**Comment by rfay** [comment] 2024-02-10 18:52
I'm having no trouble with regular zsh (not oh-my-zsh).  `brew install zsh-completions` needs to be installed, then `brew install ddev` installs `ddev` into `/opt/homebrew/share/zsh/site-functions`

My .zshrc does this, as suggested by `brew info zsh-completions`:
```
# zsh completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz compinit
    compinit
  fi
```

My FPATH ends up with something that points to where the ddev autocompletions are stored:
```
% echo $FPATH
/opt/homebrew/share/zsh/site-functions:/opt/homebrew/share/zsh-completions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.9/functions
```

I do agree that the name of the file should be `_ddev` instead of `ddev`, as in https://github.com/ddev/ddev/pull/5814

**Comment by rpkoller** [comment] 2024-02-10 22:47
I was able to narrow down the root cause. If you have followed the instructions on here: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh and added
```
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
  autoload -Uz compinit
  compinit
fi
```
to .zshrc then there following steps make zsh work and illustrate the root cause. 

1. go to `/opt/homebrew/Cellar/ddev/[your ddev version]/share/zsh/site-function`
2. `brew unlink ddev`
3. `mv ddev _ddev`
4. `brew link ddev`
5. `rm -f ~/.zcompdump compinit`

now the symlink in `/opt/homebrew/share/zsh/site-functions` is following the naming convention: 
```
lrwxr-xr-x  1 rkoller  admin    64B Feb 10 23:17 _ddev -> ../../../Cellar/ddev/HEAD-03a14bb/share/zsh/site-functions/_ddev
```
and the autocomplete auslo for for example the command ddev is working. so https://github.com/ddev/ddev/pull/5814 will probably fix things for zsh out of the box, no need for oh my zsh or zsh-completions. the only necessary thing to do is adding the snippet from above to .zshrc.

**Comment by rpkoller** [comment] 2024-02-11 17:53
Wrote up a more extensive summary of the findings in here: https://gist.github.com/rpkoller/fe5be1362b5643bb2f7d81e3eac1e852

**Comment by rfay** [comment] 2024-02-12 18:33
This was fixed in
* https://github.com/ddev/ddev/pull/5814

I know we have docs followups, but everything here is fixed, right? Closing.

**Closed by rfay** 2024-02-12 18:33 UTC

**Comment by rpkoller** [comment] 2024-02-12 18:36
Plus in https://github.com/ddev/homebrew-ddev/pull/49 and https://github.com/ddev/homebrew-ddev-edge/pull/3 . But yes the issue can be closed.
