### ISSUE TITLE
Global commands (~/.ddev/commands) don't support symbolic links

### ISSUE THREAD

**Issue by nd-** [ddev/ddev#5925] opened 2024-03-03 18:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have a bash script that I can copy in `~/.ddev/commands/web/` and launch with ddev, everything's fine.
But when I make a symlink from the script into `~/.ddev/commands/web/`, ddev can't find the command anymore.

This script is versioned in a git repository, so it would be easier for me to clone/update it somewhere, with a symbolic link in ddev commands.

### Describe your solution

Treat symlinks in `~/.ddev/commands/web/` the same way as physical files in this directory.

**Comment by rfay** [comment] 2024-03-03 18:58
If you're nice to @GuySartorelli he might do this, or you could. 

Symlinks are in fact resolved in ~/.homeadditions, so that may be a useful example.

Also note that some teams check in the global ~/.ddev/commands so they can keep these in sync with each other.

**Comment by GuySartorelli** [comment] 2024-03-03 20:07
This is a duplicate of https://github.com/ddev/ddev/issues/5806

**Comment by rfay** [comment] 2024-03-03 20:08
Awesome, thanks. Closing in favor of 
* #5806

**Closed by rfay** 2024-03-03 20:08 UTC
Labels: enhancement
