### ISSUE TITLE
show the sqlite version in output of `describe`

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#6350] opened 2024-06-25 13:52 UTC
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

The `ddev describe` status gives the versions of things in the web container, such as PHP and NodeJS.

Since sqlite is included in this, it could be useful to show that too.

### Actual Behavior

```
├──────────┼──────┼─────────────────────────────────────────────────────────────────┼────────────────────┤
│ web      │ OK   │ https://drupal-core-development-project.ddev.site               │ drupal PHP8.3      │
│          │      │ InDocker: web:443,80,8025                                       │ nginx-fpm          │
│          │      │ Host: 127.0.0.1:32802,32803                                     │ docroot:'web'      │
│          │      │                                                                 │ Perf mode: mutagen │
│          │      │                                                                 │ NodeJS:18          │
├──────────┼──────┼─────────────────────────────────────────────────────────────────┼────────────────────┤
```

### Steps To Reproduce

1. do `ddev describe`

**Comment by rfay** [comment] 2024-06-25 14:13
DDEV does not have explicit support for the sqlite type (even though it has all the capabilities obviously.)

This is a duplicate of
* https://github.com/ddev/ddev/issues/6147

**Closed by rfay** 2024-06-25 14:13 UTC

**Comment by joachim-n** [comment] 2024-06-25 14:56
Sure, but it's listed as one of the developer tools in the web image on https://ddev.readthedocs.io/en/stable/users/usage/developer-tools/

**Comment by rfay** [comment] 2024-06-25 15:04
sqlite is there in the web container and fully usable. But it's not an explicit database type. That's why the other issue is the relevant one.

**Comment by rpkoller** [comment] 2024-06-25 15:23
but as it is part of the web container i think it might make sense to list sqlite in the info section. (at least for drupal users it might be an information of interest to a certain degree) but i also agree that the cleaner approach in the long run might be a dedicated database type. both make sense to me tbh

**Comment by rfay** [comment] 2024-06-25 15:32
Sorry, I don't know how to do it without making sqlite a first-class database type. I understand that it sounds trivial to you. But it means handling settings, adding it to configuration options (`database` option in config.yaml) and much more. Contributions are welcome, but this is never used anywhere except Drupal, and there only for core dev. It's pretty much an oddball.

**Comment by joachim-n** [comment] 2024-06-26 07:02
Thanks for the explanation @rfay. Given that, I can see makes sense to only do this if #6147 is done.
