### ISSUE TITLE
Can't curl ddev sites with built-in curl in macOS 13.2.1 and traditional ddev-router

### ISSUE THREAD

**Issue by deviantintegral** [ddev/ddev#4688] opened 2023-03-01 15:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

This appears to be the same error reported in this closed issue: https://github.com/drud/ddev/issues/4427

### Run a Diagnostic and Paste Link Here

```
ddev version
 ITEM             VALUE
 DDEV version     v1.21.4
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4
 docker           20.10.20
 docker-compose   v2.14.0
 docker-platform  colima
 mutagen          0.16.0
 os               darwin
 router           drud/ddev-router:v1.21.4
 web              drud/ddev-webserver:v1.21.4
```

`ddev debug test` contains a bunch of client names i would need to redact, so let me know if there's anything specific in there I should pull out.

### Expected Behavior

I expect to be able to use curl out of the box on my host OS to interact with a project.

### Actual Behavior

`/usr/bin/curl` throws an error, while that shipped with Homebrew works. Note curl is keg-only in homebrew, so it's not easy to switch. `wget` also works fine.

### Steps To Reproduce

Create and run a project like this.

```
mkdir -p ddev-curl-test \
&& cd ddev-curl-test \
&& ddev config \
&& echo "<?php
phpinfo();" > index.php \
&& ddev start \
&& curl -v https://ddev-curl-test.ddev.site/ > /dev/null

Creating a new ddev project config in the current directory (/Users/andrew/Desktop/ddev-curl-test)
Once completed, your configuration will be written to /Users/andrew/Desktop/ddev-curl-test/.ddev/config.yaml

Project name (ddev-curl-test):

The docroot is the directory from which your site is served.
This is a relative path from your project root at /Users/andrew/Desktop/ddev-curl-test
You may leave this value blank if your site files are in the project root
Docroot Location (current directory):
Found a php codebase at /Users/andrew/Desktop/ddev-curl-test.
Project Type [backdrop, craftcms, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (php):
Configuration complete. You may now run 'ddev start'.
Starting ddev-curl-test...
Network ddev-ddev-curl-test_default  Created
Container ddev-ddev-curl-test-dba  Started
Container ddev-ddev-curl-test-web  Started
Container ddev-ddev-curl-test-db  Started
You have mutagen enabled and your 'php' project type doesn't have an upload_dir set.
For faster startup and less disk usage,
set upload_dir to where your user-generated files are stored.
Starting mutagen sync process... This can take some time.
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st ddev-curl-test -l'
Container ddev-router  Running
Successfully started ddev-curl-test
Project can be reached at https://ddev-curl-test.ddev.site https://127.0.0.1:49187
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:443...
* Connected to ddev-curl-test.ddev.site (127.0.0.1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
} [329 bytes data]
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ddev-curl-test.ddev.site:443
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ddev-curl-test.ddev.site:443
```

curl info:

```
$ which curl
/usr/bin/curl
$ curl --version
curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
```

Trying with homebrew curl:

```
/opt/homebrew/Cellar/curl/7.88.1/bin/curl -v https://ddev-curl-test.ddev.site > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:443...
* Connected to ddev-curl-test.ddev.site (127.0.0.1) port 443 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1144 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: O=mkcert development certificate; OU=root@b70f8483da18
*  start date: Mar  1 15:15:06 2023 GMT
*  expire date: Jun  1 15:15:06 2025 GMT
*  subjectAltName: host "ddev-curl-test.ddev.site" matched cert's "ddev-curl-test.ddev.site"
*  issuer: O=mkcert development CA; OU=andrew@acutus-498.local (Andrew Berry); CN=mkcert andrew@acutus-498.local (Andrew Berry)
*  SSL certificate verify ok.
} [5 bytes data]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: ddev-curl-test.ddev.site]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x148013000)
} [5 bytes data]
> GET / HTTP/2
> Host: ddev-curl-test.ddev.site
> user-agent: curl/7.88.1
> accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 200
< server: nginx/1.20.1
< date: Wed, 01 Mar 2023 15:16:45 GMT
< content-type: text/html; charset=UTF-8
< vary: Accept-Encoding
<
{ [16283 bytes data]
100  116k    0  116k    0     0  3831k      0 --:--:-- --:--:-- --:--:-- 4152k
* Connection #0 to host ddev-curl-test.ddev.site left intact
```

### Anything else?

This worked at some point in the past few months. I wonder if a macOS `13.x` update changed things, or if my switch from amd64 to arm64 is at all related.

I also tried downgrading Homebrew's curl to 7.86.0, but it worked fine.

I wondered if there was something up with TLS negotiation. While I can see a TLS 1.3 connection being established when curl'ing google, if I specify it I get an error:

```
curl --tlsv1.3 -v https://www.google.com/
*   Trying [2607:f8b0:400b:804::2004]:443...
* Connected to www.google.com (2607:f8b0:400b:804::2004) port 443 (#0)
* Closing connection 0
curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

If I cap TLS 1.2, curl works:

```
curl --tls-max 1.2 -kv https://ddev-curl-test.ddev.site
```

So honestly, I think this is likely a bug in the macOS curl, and not in ddev. But, it'd be great to know if anyone else can reproduce, and if anyone is lagging on security updates if it works in older Ventura releases.

**Comment by rfay** [comment] 2023-03-01 16:11
Thanks for the report! Some of us have had nagging problems with curl periodically, including the homebrew curl.

**Comment by rfay** [comment] 2023-03-01 23:06
I can reproduce this using traditional router:

```
$ /usr/bin/curl -I https://d9.ddev.site
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to d9.ddev.site:443
```

However it works fine using traefik router:

```
$ /usr/bin/curl -I https://d9.ddev.site
HTTP/2 200
cache-control: must-revalidate, no-cache, private
content-language: en
content-type: text/html; charset=UTF-8
date: Wed, 01 Mar 2023 23:00:24 GMT
expires: Sun, 19 Nov 1978 05:00:00 GMT
server: nginx
vary: Accept-Encoding
x-content-type-options: nosniff
x-drupal-cache: MISS
x-drupal-dynamic-cache: MISS
x-frame-options: SAMEORIGIN
x-generator: Drupal 9 (https://www.drupal.org)
x-ua-compatible: IE=edge
```

So another good reason to move on to the traefik router, which will be default in v1.22, 

* https://github.com/drud/ddev/issues/4679

However, I imagine this is just a tad of nginx config in the traditional ddev-router.

**Comment by rfay** [comment] 2023-04-01 16:15
I'm going to close this because the future is with Traefik and I don't see this issue with the traefik router.  Thanks for the thoughtful investigation and documentation.

**Closed by rfay** 2023-04-01 16:15 UTC

**Comment by rfay** [comment] 2023-10-12 18:25
@woodyc79 that doesn't seem related to the issue here. Please open a new issue or else explain what you're trying to curl and where. Please say if you're trying to curl `*.ddev.site` or something external, and give an example in your new issue. When you create the new issue, please make sure to provide the requested output of `ddev debug test`
