### ISSUE TITLE
GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key 

### ISSUE THREAD

**Issue by acividini92** [ddev/ddev#6028] opened 2024-03-28 17:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project flyontario-d9: [/home/andreacividini/projects/flyontario/flyontario-d9/.ddev/config.yaml]
name: flyontario-d9
type: drupal9
docroot: web
php_version: 8.1
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.4
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
mariadb_version: 10.3
database: {mariadb 10.3}
hooks: map[pre-import-db:[map[exec-host:fru cloud:db:dl -f flyod9.sql.gz flyod9 || exit 1;]]]
omit_containers: [dba]
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
webimage_extra_packages: [build-essential wait-for-it]
project_tld: ddev.site
use_dns_when_possible: true
timezone: America/Los_Angeles
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-26670 in ../tryddevproject-26670 =========
OS Information: Linux andrea-cividini 6.8.0-76060800daily20240311-generic #202403110203~1710198088~22.04~1a3dbc7~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1001(andreacividini) gid=1001(andreacividini) groups=1001(andreacividini),4(adm),27(sudo),120(lpadmin),998(docker)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.4                                 
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4             
 docker           26.0.0                                  
 docker-compose   v2.14.0                                 
 docker-platform  andrea-cividini                         
 mutagen          0.16.0                                  
 os               linux                                   
 router           drud/ddev-router:v1.21.4                
 web              drud/ddev-webserver:v1.21.4             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 36990400 Mar 20 16:17 /usr/bin/docker
docker version: 
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:17:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:48 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.16.0
--------------------------------------------------------------------------------
Name: native
Identifier: sync_u0oLmnYtyuwD2GuwcyAZYfZbeylZUxKY3AF8trpdvrA
Labels:
	com.ddev.volume-signature: var-run-1707912353
Configuration:
	Synchronization mode: Two Way Resolved
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: POSIX Raw
	Ignore VCS mode: Default (Propagate)
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/docroot/wp-content/uploads
	Permissions mode: Default (Portable)
Alpha:
	URL: /home/andreacividini/projects/wordpress/native-camper-vans
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Beta:
	URL: docker://ddev-native-web/var/www/html
		DOCKER_HOST=unix:///var/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: Default (10 seconds)
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: No
Status: [Paused]
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: andrea-cividini 
Using docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.14.0 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 26.0.0 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 214.6G    197.7G      5.9G  97% /

unable to create project at project root '/home/andreacividini/projects/wordpress/aprd': project root /home/andreacividini/projects/wordpress/aprd does not exist
Stopped mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers: 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/home/andreacividini/projects/flyontario/tryddevproject-26670) 
Once completed, your configuration will be written to /home/andreacividini/projects/flyontario/tryddevproject-26670/.ddev/config.yaml
 
Configuring unrecognized codebase as project type 'php' at /home/andreacividini/projects/flyontario/tryddevproject-26670/web 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-26670... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Network ddev-tryddevproject-26670_default  Created 
Container ddev-tryddevproject-26670-db  Started 
Container ddev-tryddevproject-26670-dba  Started 
Container ddev-tryddevproject-26670-web  Started 
Container ddev-router  Started 
Successfully started tryddevproject-26670 
Project can be reached at https://tryddevproject-26670.ddev.site https://127.0.0.1:32771 
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 28 Mar 2024 17:07:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-26670.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 28 Mar 2024 17:07:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-26670.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-26670'
======== Project ownership on host:
drwxr-xr-x 4 andreacividini andreacividini 4096 Mar 28 18:06 ../tryddevproject-26670
======== Project ownership in container:
drwxr-xr-x 4 andreacividini andreacividini 4096 Mar 28 17:06 /var/www/html
======== In-container filesystem:
Filesystem     Type 1K-blocks      Used Available Use% Mounted on
/dev/sda2      ext4 225002092 207537936   5961872  98% /var/www/html
======== curl again of tryddevproject-26670 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-26670'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-26670'
Opening in existing browser session. 
```
</details>         

### Expected Behavior

Running `ddev start` would start my project. The project has been running up to 15 minutes before I started having this issue.
I run a ddev poweroff and after that the issue started happening. It's taking place on all my PHP projects.

### Actual Behavior

I get this output (copied in full, the error part #13.
I tried removing the extra packages from `webimage_extra_packages` fomr ddev project config, but it's still happening.

```
failed to solve: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests build-essential wait-for-it" did not complete successfully: exit code: 100 
Failed to start flyontario-d9: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-flyontario-d9 docker-compose -f /home/andreacividini/projects/flyontario/flyontario-d9/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 591B done
#1 DONE 0.1s

#2 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#2 DONE 0.0s

#3 [drud/ddev-webserver:v1.21.4-flyontario-d9-built internal] load build definition from Dockerfile
#3 transferring dockerfile: 1.76kB done
#3 DONE 0.2s

#4 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.2s

#5 [drud/ddev-webserver:v1.21.4-flyontario-d9-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#6 DONE 0.0s

#7 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built 2/2] RUN (groupadd --gid 1001 "andreacividini" || groupadd "andreacividini" || true) && (useradd  -l -m -s "/bin/bash" --gid "andreacividini" --comment '' --uid 1001 "andreacividini" || useradd  -l -m -s "/bin/bash" --gid "andreacividini" --comment '' "andreacividini" || useradd  -l -m -s "/bin/bash" --gid "1001" --comment '' "andreacividini" || useradd -l -m -s "/bin/bash" --comment '' andreacividini )
#7 CACHED

#8 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built] exporting to image
#8 exporting layers done
#8 writing image sha256:22336754e1bca35b783c48369c40be99a6433dcaf68071cb714ec2c6549bd6ad 0.0s done
#8 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built
#8 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4-flyontario-d9-built 0.0s done
#8 DONE 0.1s

#9 [drud/ddev-webserver:v1.21.4-flyontario-d9-built internal] load .dockerignore
#9 transferring context: 2B done
#9 DONE 0.1s

#10 [drud/ddev-webserver:v1.21.4-flyontario-d9-built 1/8] FROM docker.io/drud/ddev-webserver:v1.21.4
#10 DONE 0.0s

#11 [drud/ddev-webserver:v1.21.4-flyontario-d9-built 2/8] RUN (groupadd --gid 1001 "andreacividini" || groupadd "andreacividini" || true) && (useradd  -l -m -s "/bin/bash" --gid "andreacividini" --comment '' --uid 1001 "andreacividini" || useradd  -l -m -s "/bin/bash" --gid "andreacividini" --comment '' "andreacividini" || useradd  -l -m -s "/bin/bash" --gid "1001" --comment '' "andreacividini" || useradd -l -m -s "/bin/bash" --comment '' andreacividini )
#11 CACHED

#12 [drud/ddev-webserver:v1.21.4-flyontario-d9-built internal] load build context
#12 transferring context: 215B done
#12 DONE 0.1s

#13 [drud/ddev-webserver:v1.21.4-flyontario-d9-built 3/8] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential wait-for-it
#13 5.736 W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
#13 5.736 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
#13 ERROR: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests build-essential wait-for-it" did not complete successfully: exit code: 100
------
 > [drud/ddev-webserver:v1.21.4-flyontario-d9-built 3/8] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential wait-for-it:
#13 5.736 W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
#13 5.736 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
------
', stderr='failed to solve: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests build-essential wait-for-it" did not complete successfully: exit code: 100' 
```

### Steps To Reproduce

Running `ddev start` with ddev version v1.21.4 on any PHP based project fails with the above message.

### Anything else?

I also noticed this weird diference

➜  sudo apt install ddev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ddev is already the newest version (1.22.7).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
➜   ddev --version
ddev version v1.21.4

**Comment by rfay** [comment] 2024-03-28 17:17
Duplicate of the pinned issue
* https://github.com/ddev/ddev/issues/5795

Please search issues before you post an issue.

You need to update your DDEV to current v1.22.7 and not use super-old v1.21.4.

**Closed by rfay** 2024-03-28 17:17 UTC

**Comment by stasadev** [comment] 2024-03-28 18:36
> I also noticed this weird diference
➜ sudo apt install ddev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ddev is already the newest version (1.22.7).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
➜ ddev --version
ddev version v1.21.4

See https://ddev.readthedocs.io/en/latest/users/usage/faq/#why-do-i-have-an-old-ddev
