### ISSUE TITLE
DDEV project stops unpredictably for no known reason

### ISSUE THREAD

**Issue by zaifastafa** [ddev/ddev#5682] opened 2024-01-08 08:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
huzaifa@huzaifamustafa:~/code/shopware$ ddev debug test
Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project shopware: [/home/huzaifa/code/shopware/.ddev/config.yaml]
name: shopware
type: shopware6
docroot: public
php_version: 8.2
webserver_type: apache-fpm
webimage: ddev/ddev-webserver:v1.22.6
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mysql 8.0}
omit_containers: [dba]
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 18
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-27791 in ../tryddevproject-27791 =========
OS Information: Linux huzaifamustafa 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(huzaifa) gid=1000(huzaifa) groups=1000(huzaifa),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.22.6                                 
 architecture     amd64                                   
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.6 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.6             
 docker           24.0.7                                  
 docker-compose   v2.23.3                                 
 docker-platform  linux-docker                            
 mutagen          0.17.2                                  
 os               linux                                   
 router           ddev/ddev-traefik-router:v1.22.6        
 web              ddev/ddev-webserver:v1.22.6             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.23.3
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35948624 Oct 26 14:08 /usr/bin/docker
docker version: 
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: linux-docker 
Using Docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.23.3 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 24.0.7 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 

```
</details>         

### Expected Behavior

Project should keep running until stopped explicitly. 

### Actual Behavior

Sometimes the project stops on its own. When running the any command like `ddev exec bin/console` out of nowhere while working, it tells me that the project is not running and I should run ddev start.

```
$ ddev exec bin/console pl:ref
Project is not currently running. Try 'ddev start'.
```
this is quite annoying to be honest. It was doing the same thing when I was running the supervisor commands when a time limit of the messener:consume command reached its limit and the command stopped then the whole container was stopping. So I tried using the ddev-cron addon, but that was giving the same issue that out of nowhere suddently the project stopped working. So I removed the ddev-cron addon but I am still getting the issue. 

### Steps To Reproduce

Unfortunately there are no specific steps that I know of that causes it because the reason is unknown to me. As said above, it did happen when using supervisor conf, then I moved to ddev-cron and I then removed the addon but it still is causing the problems.

**Comment by stasadev** [comment] 2024-01-08 19:00
Hi @zaifastafa,

Unfortunately, I can't guess the source of the problem. I think you are on the right track with the supervisor, but who knows.

Have a look at the logs next time you encounter this issue:

```
ddev logs
```

You can also collect logs using Docker:

```
# get the web container id
docker ps -a
# and pass it here
docker logs <container-id>
```

**Comment by rfay** [comment] 2024-01-09 10:54
The most common reason for this kind of thing is a system restart or a docker restart, or docker exiting. 

As @stasadev says, `ddev logs` should show you why. `ddev list` should show you the current situation.

If you're able to recreate this with a plain-vanilla project it will be interesting to look at. 

(I note you have a very old config, which has `omit_containers: [dba]`. It does no harm, but why don't you do a `ddev config --auto` to update it.)

In your `ddev debug test` you left off a huge part of the output, so I can't study everything I would normally look at.

**Comment by rfay** [comment] 2024-01-09 12:54
This output is not standard DDEV output, 

> Process: Require is used /tmp/37b0aa2e-80ef-429f-81ef-c22557584da1/
{"success":true,"message":{"version":"5.1.6"}}
Process 1704800038244 heartbeat: "alive" 
Process 1704800038244 heartbeat: "alive" 
Process 1704800038244 heartbeat: "alive" 
Process 1704800038244 heartbeat: "alive" 


I assume you must have a web_extra_daemons configured, or are otherwise running an extra daemon using supervisord? Your daemon is crashing, I think, and that brings it all down.

**Comment by zaifastafa** [comment] 2024-01-09 13:14
@rfay No, my web_extra_daemons section of the config is commented out. And there is no additional configuration setup for supervisor either (except if something is running by default then I dont know) I was using the ddev-cron addon as mentioned in the desciption, but then it was also crashing for some reason, so I removed it, and I deleted all the images and then started them again - and the above output is after that.

**Comment by rfay** [comment] 2024-01-09 13:28
When you restart it, please do `ddev logs` and take a look to find out what process is emitting those messages.

Something is saying `Process 1704800038244 heartbeat: "alive"`, you have some process that emits information about a heartbeat. I imagine it is a process where the heartbeat is eventually failing and bringing down the system.

Maybe you can provide any `.ddev/config.*.yaml` or `.ddev/docker-compose.*.yaml` that you have in there.

Part of the debugging process here is to limit your custom configuration to try to figure out what's going on.
`

**Comment by zaifastafa** [comment] 2024-01-09 13:35
I just have the watcher yaml file from susi dev

```
services:
    web:
        expose:
            # Storefront Hot Proxy Ports
            - 9997
            - 9998
            - 9999
        environment:
            # Shopware Administration Watch Host
            - HOST=0.0.0.0
            # Shopware Administration Watch Port
            - PORT=9997
            # Expose APP_URL to administration watcher
            - APP_URL=http://shopware.ddev.site
            - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,9998:9998,9997:9997
            - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,8888:9998,8887:9997

```

**Comment by rfay** [comment] 2024-01-09 13:37
How are you starting the watcher? I imagine it's old-fashioned, installed directly into supervisord, and it's failing. I think you probably have a .ddev/web-build/Dockerfile that's installing it.

**Comment by zaifastafa** [comment] 2024-01-09 13:39
Does this logs make sense to you? This is when the container is running: 

```
huzaifa@huzaifamustafa:~/code/shopware$ ddev logs
+ set -eu -o pipefail
+ logpipe=/var/tmp/logpipe
+ [[ ! -p /var/tmp/logpipe ]]
+ mkfifo /var/tmp/logpipe
+ trap 'trap - SIGTERM && kill -- -1' SIGINT SIGTERM EXIT SIGHUP SIGQUIT
+ cat
+ set -o errexit nounset pipefail
+ rm -f /tmp/healthy
+ pkill -0 supervisord
+ rm -f /var/run/supervisor.sock
+ export DDEV_WEB_ENTRYPOINT=/mnt/ddev_config/web-entrypoint.d
+ DDEV_WEB_ENTRYPOINT=/mnt/ddev_config/web-entrypoint.d
+ source /functions.sh
+ '[' '!' -f /home/huzaifa/.gitconfig ']'
+ DDEV_PHP_VERSION=8.2
+ DDEV_WEBSERVER_TYPE=apache-fpm
+ '[' -n 8.2 ']'
+ update-alternatives --set php /usr/bin/php8.2
update-alternatives: using /usr/bin/php8.2 to provide /usr/bin/php (php) in manual mode
update-alternatives: warning: skip creation of /usr/share/man/man1/php.1.gz because associated file /usr/share/man/man1/php8.2.1.gz (of link group php) doesn't exist
+ ln -sf /usr/sbin/php-fpm8.2 /usr/sbin/php-fpm
+ export PHP_INI=/etc/php/8.2/fpm/php.ini
+ PHP_INI=/etc/php/8.2/fpm/php.ini
+ '[' '!' -z ']'
+ '[' -d /mnt/ddev_config/php ']'
++ ls -A /mnt/ddev_config/php/my-php.ini
+ '[' -n /mnt/ddev_config/php/my-php.ini ']'
+ cp /mnt/ddev_config/php/my-php.ini /etc/php/8.2/cli/conf.d/
+ cp /mnt/ddev_config/php/my-php.ini /etc/php/8.2/fpm/conf.d/
+ '[' -d /mnt/ddev_config/nginx_full ']'
+ rm -rf /etc/nginx/sites-enabled
+ cp -r /mnt/ddev_config/nginx_full /etc/nginx/sites-enabled/
+ '[' -d /mnt/ddev_config/apache ']'
+ rm -rf /etc/apache2/sites-enabled
+ cp -r /mnt/ddev_config/apache /etc/apache2/sites-enabled
+ '[' shopware6 = backdrop ']'
+ '[' shopware6 = drupal6 ']'
+ '[' shopware6 = drupal7 ']'
+ '[' shopware6 = backdrop ']'
++ id -un
++ id -gn
+ printf '\nexport APACHE_RUN_USER=huzaifa\nexport APACHE_RUN_GROUP=huzaifa\n'
+ a2enmod access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex deflate dir env filter mime mpm_prefork negotiation reqtimeout rewrite setenvif status
Considering dependency authn_core for access_compat:
Module authn_core already enabled
Module access_compat already enabled
Module alias already enabled
Considering dependency authn_core for auth_basic:
Module authn_core already enabled
Module auth_basic already enabled
Module authn_core already enabled
Module authn_file already enabled
Module authz_core already enabled
Considering dependency authz_core for authz_host:
Module authz_core already enabled
Module authz_host already enabled
Considering dependency authz_core for authz_user:
Module authz_core already enabled
Module authz_user already enabled
Module autoindex already enabled
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
Module dir already enabled
Module env already enabled
Module filter already enabled
Module mime already enabled
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Enabling module mpm_prefork.
Module negotiation already enabled
Module reqtimeout already enabled
Enabling module rewrite.
Module setenvif already enabled
Module status already enabled
To activate the new configuration, you need to run:
  service apache2 restart
+ a2enconf charset localized-error-pages other-vhosts-access-log security serve-cgi-bin
Conf charset already enabled
Conf localized-error-pages already enabled
Conf other-vhosts-access-log already enabled
Conf security already enabled
Conf serve-cgi-bin already enabled
+ '[' apache-fpm = apache-fpm ']'
+ a2enmod proxy_fcgi
Considering dependency proxy for proxy_fcgi:
Enabling module proxy.
Enabling module proxy_fcgi.
To activate the new configuration, you need to run:
  service apache2 restart
+ a2enconf php8.2-fpm
Enabling conf php8.2-fpm.
To activate the new configuration, you need to run:
  service apache2 reload
+ a2dissite 000-default
Site 000-default already disabled
+ '[' false = true ']'
+ disable_xdebug
Disabled xdebug
+ phpenmod assert
+ ls /var/www/html
+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
+ sudo mkdir -p /mnt/ddev-global-cache/bashhistory/shopware-web /mnt/ddev-global-cache/mysqlhistory/shopware-web /mnt/ddev-global-cache/nvm_dir/shopware-web /mnt/ddev-global-cache/npm /mnt/ddev-global-cache/yarn/classic /mnt/ddev-global-cache/yarn/berry
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /mnt/ddev-global-cache/ /var/lib/php
+ cd /home/huzaifa
+ exit 22
+ true
+ mkdir -p /home/huzaifa/.yarn/berry
+ ln -sf /mnt/ddev-global-cache/yarn/berry /home/huzaifa/.yarn/berry/cache
+ ln -sf /mnt/ddev-global-cache/nvm_dir/shopware-web /home/huzaifa/.nvm
+ '[' '!' -f /home/huzaifa/.nvm/nvm.sh ']'
+ '[' -d /mnt/ddev_config/.homeadditions ']'
+ cp -r /mnt/ddev_config/.homeadditions/. /home/huzaifa/
+ sudo mkdir -p /mnt/ddev-global-cache/mkcert
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /mnt/ddev-global-cache/
+ '[' '!' -f /mnt/ddev-global-cache/mkcert/rootCA.pem ']'
+ mkcert -install
The local CA is now installed in the system trust store! ⚡️

+ CAROOT=/mnt/ddev-global-cache/mkcert
+ mkcert -cert-file /etc/ssl/certs/master.crt -key-file /etc/ssl/certs/master.key shopware.ddev.site localhost 127.0.0.1 127.0.0.1 web ddev-shopware-web ddev-shopware-web.ddev

Created a new certificate valid for the following names 📜
 - "shopware.ddev.site"
 - "localhost"
 - "127.0.0.1"
 - "127.0.0.1"
 - "web"
 - "ddev-shopware-web"
 - "ddev-shopware-web.ddev"

The certificate is at "/etc/ssl/certs/master.crt" and the key at "/etc/ssl/certs/master.key" ✅

It will expire on 9 April 2026 🗓

+ echo 'Server started'
Server started
+ unset PHP_IDE_CONFIG
+ ddev_python_setup
+ set -e
+ '[' apache-fpm = nginx-gunicorn ']'
+ set +e
+ ddev_custom_init_scripts
+ echo 'Loading custom entrypoint config from /mnt/ddev_config/web-entrypoint.d'
Loading custom entrypoint config from /mnt/ddev_config/web-entrypoint.d
+ ls '/mnt/ddev_config/web-entrypoint.d/*.sh'
+ logpipe=/var/tmp/logpipe
+ [[ ! -p /var/tmp/logpipe ]]
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-apache-fpm.conf
2024-01-09 13:02:50,961 INFO Included extra file "/etc/supervisor/apache.conf" during parsing
2024-01-09 13:02:50,961 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2024-01-09 13:02:50,961 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2024-01-09 13:02:50,961 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2024-01-09 13:02:50,965 INFO RPC interface 'supervisor' initialized
2024-01-09 13:02:50,965 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-01-09 13:02:50,965 INFO supervisord started with pid 42
2024-01-09 13:02:51,970 INFO spawned: 'child_exit_monitor' with pid 2063
2024-01-09 13:02:51,976 INFO spawned: 'php-fpm' with pid 2064
2024-01-09 13:02:51,984 INFO spawned: 'apache2' with pid 2065
2024-01-09 13:02:51,992 INFO spawned: 'mailpit' with pid 2066
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.8. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 09 13:02:52.113026 2024] [ssl:warn] [pid 2074] AH01909: 172.21.0.8:443:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.8. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 09 13:02:52.123502 2024] [ssl:warn] [pid 2074] AH01909: 172.21.0.8:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jan 09 13:02:52.126213 2024] [mpm_prefork:notice] [pid 2074] AH00163: Apache/2.4.56 (Debian) OpenSSL/1.1.1w configured -- resuming normal operations
[Tue Jan 09 13:02:52.126249 2024] [core:notice] [pid 2074] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[09-Jan-2024 13:02:52] NOTICE: fpm is running, pid 2064
[09-Jan-2024 13:02:52] NOTICE: ready to handle connections
[09-Jan-2024 13:02:52] NOTICE: systemd monitor interval set to 10000ms
2024-01-09 13:02:53,185 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-09 13:02:53,186 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-09 13:02:53,186 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-09 13:02:53,186 INFO success: mailpit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```

**Comment by zaifastafa** [comment] 2024-01-09 13:41
> How are you starting the watcher? I imagine it's old-fashioned, installed directly into supervisord, and it's failing. I think you probably have a .ddev/web-build/Dockerfile that's installing it.

```
$ ddev composer watch:admin
```

The watcher is not doing anything in the Dockerfile. I just have Dockerfile.example in the web-build folder. I am not running a supervisor command here or extending Dockerfile. The yaml file is just exposing the ports for the watcher to run correctly. 

Here is the link for reference: https://susi.dev/ddev-shopware-6/

**Comment by rfay** [comment] 2024-01-09 13:45
At this time your process has not yet started doing its heartbeat check, whatever it is- you'll want to see if you can do a `ps -fp <process-id>` when you see that in the logs. It's there in the failure. 

I don't know if watcher can bring down the system, don't know how it could. 

But you definitely have something in there running, and it has a heartbeat, and typically things that have heartbeats fail when the heartbeat fails.

You're not suspending your laptop are you? That would be a classic way for it to fail.

**Comment by zaifastafa** [comment] 2024-01-09 13:48
Is there a way to clean the project and start from fresh? I have already deleted the images and started it, but I dont think it helped. Is there some thing else that I can flush out just to get a stock ddev instance? If I delete the `.ddev` directory and delete the images, will it help?

**Comment by rfay** [comment] 2024-01-09 13:50
The images are not related, they will just be downloaded again and will be exactly the same.

If you want to blow away your project, then `ddev delete` and then remove as much of your custom configuration as you can, and then reconfigure it. Yes, you can `rm -r .ddev` and start again with `ddev config`. But do check in your work first so you can compare.

You definitely have something running in the web container that has heartbeats.

**Comment by zaifastafa** [comment] 2024-01-09 14:06
OK, in the meantime, can you tell me how can I then run supervisor kind of services without crashing the project?

**Comment by rfay** [comment] 2024-01-09 14:23
AFAIK supervisor doesn't emit messages like you show. Maybe I'm wrong.

**Comment by rfay** [comment] 2024-01-09 14:49
I think you should do a `ddev exec ps -ef` after starting and using your project to see what processes are running.

**Comment by zaifastafa** [comment] 2024-01-10 05:38
@rfay There is nothing I could see that is running out of the ordinary. It just happened again right now. Strange thing is, that the project is accessible via the URL and everything seems to be working - but when I use ddev exec command, it says Project is not currently running. Try 'ddev start'. I am using a fresh Shopware installation right now with no configurations like adminer or watcher so I dont think its something related to that. Project is also running in the browser, but the CLI says project is not running. 
If I ping the project, I get success as well, so I cannot understand why ddev exec bin/console is saying project not running. If I do ddev ssh I get this instead: 

```
huzaifa@huzaifamustafa:~/code/shopware$ ddev ssh
huzaifa@shopware-web:/tmp/28fa0801-4be0-4456-b16e-c894184a5a7d$ 
```

Some kind of temp folder.

**Comment by rfay** [comment] 2024-01-10 10:57
If `ddev ssh` lands you in a temp folder, it's because of your configuration. It would normally land in /var/www/html

Please do see if you can create a standard plain-vanilla shopware project and use it. Then add configuration to it one thing at a time. You apparently have lots of "interesting" configuration. There's no way you should `ddev ssh` and land in a temp folder. Maybe you have configuration in ~/.ddev/homeadditions, or in .ddev/homeadditions.

I do think it's a good idea to check your code in and then `mv ~/.ddev ~/.ddev.bak` and `mv .ddev .ddev.bak` to get completely new configuration with `ddev config` and then see what happens. Then you can add your custom configuration back in one thing at a time.

**Comment by zaifastafa** [comment] 2024-01-10 12:30
Yes I know that's the problem I am highlighting. When the CLI says project not running, I do a dev ssh and find myself in a temp folder. I have already done a fresh installation and deleted the .ddev folder, the images, and started fresh with --auto config.

**Comment by rfay** [comment] 2024-01-11 01:36
You're doing a `ddev ssh` when the web container is still in the process of timing out I guess. It's not up, but `ddev ssh` is willing to take you in there. 

As said a few times, you're going to have to trim down your configuration until you figure out what is causing this problem. 

I think you've said that a normal trivial project doesn't have this behavior. So you need to remove your extra configuration (or start from scratch) until you can figure out what the problem is.

I would do a screenshare session with you to help with this, but I'm on a bicycle tour in Chile and have little availability. But I can do that with you in February.

**Comment by zaifastafa** [comment] 2024-01-16 05:13
Hi, sorry but the time difference is big. I am on UTC+5. 

By the way it is related to supervisor, and using the watch command. Those 2 seems to be causing the problem. If I do not use the watch command or have no active crons / supervisor command running, then the project stays alive and active. 

You can easily recreate this issue by setting up a shopware 6.5 installation. In the extra ports config, assign 8080:9997 and then run `ddev composer watch:admin`. After it compiles everything, you terminate the watch command then the project gets messed up. The project is stil accessible on the browser and I can access everything the backend and storefront, but it's state somehow has changed because when I ddev ssh, I get into the temp folder instead of project.

**Comment by rfay** [comment] 2024-01-19 00:19
I will be available all day tomorrow/Friday, in UTC-3. But it sounds like you have sorted everything out.

If you are able to provide a repository demonstrating this, I'll be happy to take a look also, but I can't help without at least a demonstration, and you seem to understand what's going on.

It sounds like the abandoned PR
* https://github.com/ddev/ddev/pull/5423

would have solved this, but for now your problem is (as you describe it) that you have a daemon configured in supervisord, and the daemon is exiting on you, and the current config doesn't allow that - when a daemon is started by supervisord, it needs to keep running and not die. You can change the config to a script that does something like `while true; do <somedaemon> || true>; done`

Closing for now, happy to look at it with you, happy to look at a demo repo.

**Closed by rfay** 2024-01-19 00:19 UTC

**Comment by zaifastafa** [comment] 2024-01-19 04:44
Not really sorted it out, but just figured out the problem and the PR you mentioned is exactly what is happening. If it can be incorporated somehow maybe that helps. 

The symfony messenger command should ideally be run with a time-limit or memory-limit and then it stops when that is reached. And when that does, the supervisor kills the contianer. Admin watcher in Shopware is doing similar thing since you mentioned that anything with a heartbeat needs to keep running otherwise the container dies when the heartbeat stops. 

I guess I will just try to ensure that the daemon (messenger:consume) command is executed without any time or memory limit for the time being until it is fixed in the PR. 

Thanks for taking out the time to respond. If you want to reproduce the issue you can clone this repo and set it up: https://github.com/shopware/shopware

**Comment by rfay** [comment] 2024-01-19 11:49
This absolutely isn't something that happens with plain shopware, it only happens if you implement a daemon with supervisord, which isn't done by default.

I think you probably want the solution described in discord at https://discordapp.com/channels/664580571770388500/1186671649731395595 though, 


```
#!/usr/bin/env bash

while : ; do
    php /var/www/html/shopware/bin/console messenger:consume async --time-limit=20 -n
done
```
