### ISSUE TITLE
`ddev start` fails after update to 1.23.0 (Dockerfile)

### ISSUE THREAD

**Issue by zimbar** [ddev/ddev#6135] opened 2024-04-27 10:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/usr/local/bin/ddev
/usr/bin/ddev



WARNING: Project should most often be in a subdirectory of the user's home directory.
Instead it's in /datas/phpstormProjects/lcgpro_prod_2.4.6-p4

These config files were loaded for project m246: [/datas/phpstormProjects/lcgpro_prod_2.4.6-p4/.ddev/config.yaml /datas/phpstormProjects/lcgpro_prod_2.4.6-p4/.ddev/config.m246.yaml]
name: m246
type: magento2
docroot: pub
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.0-1
router_http_port: 8080
router_https_port: 443
mariadb_version: 10.3
database: {mariadb 10.3}
hooks: map[post-start:[map[exec:bash .ddev/custom_scripts/check-ddev-version.sh]]]
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 1
disable_settings_management: true
nodejs_version: 20
default_container_timeout: 120


======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /datas/phpstormProjects/lcgpro_prod_2.4.6-p4
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-5461 in ../tryddevproject-5461 ========
Creating a new DDEV project config in the current directory (/datas/phpstormProjects/tryddevproject-5461)
Once completed, your configuration will be written to /datas/phpstormProjects/tryddevproject-5461/.ddev/config.yaml

Configuring a 'php' project with docroot 'web' at /datas/phpstormProjects/tryddevproject-5461/web
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux fedora 6.8.7-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:34:28 UTC 2024 x86_64 GNU/Linux


======== User information ========
uid=1000(ridha) gid=1000(ridha) groupes=1000(ridha),10(wheel),973(docker) contexte=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023


======== ddev version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.0                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.0 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.0              
 docker           26.1.0                                   
 docker-api       1.45                                     
 docker-compose   v2.26.1                                  
 docker-platform  linux-docker                             
 mutagen          0.17.2                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.23.0         
 web              ddev/ddev-webserver:v1.23.0-1            



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.0
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/home/ridha/.local/share/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.26.1
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=


======== DOCKER provider info ========
docker client location: /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/usr/local/bin/docker
/usr/bin/docker

Docker provider: linux-docker
docker version: 
Client: Docker Engine - Community
 Version:           26.1.0
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        9714adc
 Built:             Mon Apr 22 17:09:07 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:07:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Docker platform: linux-docker
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.26.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 26.1.0
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 222.0G    198.2G     21.0G  90% /


======== Existing docker containers ========
CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS    PORTS     NAMES
b8b5d156d652   hello-world   "/hello"   12 months ago   Created             vigilant_hopper


======== mkcert information ========
/usr/bin/mkcert
/usr/local/bin/mkcert
/usr/bin/mkcert
/home/ridha/.local/share/mkcert
total 8
-r--------. 1 ridha ridha 2484 26 juil.  2023 rootCA-key.pem
-rw-r--r--. 1 ridha ridha 1614 26 juil.  2023 rootCA.pem


======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) octets de données.
64 octets de local.oc-mall (127.0.0.1) : icmp_seq=1 ttl=64 temps=0.030 ms

--- statistiques ping dkdkd.ddev.site ---
1 paquets transmis, 1 reçus, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.030/0.030/0.030/0.000 ms


======== Project startup ========
Network ddev_default created
Starting tryddevproject-5461...
2024-04-27T11:46:41.99 Pulled image for ddev/ddev-webserver:v1.23.0-1
2024-04-27T11:46:41.991 Pulled image for busybox:stable
2024-04-27T11:46:41.998 Pulled image for ddev/ddev-ssh-agent:v1.23.0
2024-04-27T11:46:42 Pulled image for ddev/ddev-traefik-router:v1.23.0
2024-04-27T11:46:43.531 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
2024-04-27T11:46:44.36 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1000
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
2024-04-27T11:46:47.313 host.docker.internal='' runtime.GOOS==linux and docker 20.10+
2024-04-27T11:46:47.427 Pulled image for ddev/ddev-webserver:v1.23.0-1
v1.23.0: Pulling from ddev/ddev-dbserver-mariadb-10.11
bccd10f490ab: Pulling fs layer
d9d8e1823c6f: Pulling fs layer
84f2e2edb76d: Pulling fs layer
4df97d18a516: Pulling fs layer
79fe85183306: Pulling fs layer
b891b67a5cf8: Pulling fs layer
ac1d0cb433aa: Pulling fs layer
c29a5135f832: Pulling fs layer
4f4fb700ef54: Pulling fs layer
1ff4f1de0bc5: Pulling fs layer
673864f86d20: Pulling fs layer
7b45c0976273: Pulling fs layer
ca9e486aa247: Pulling fs layer
0a97e5ce4743: Pulling fs layer
bc3ffa5c64c8: Pulling fs layer
e60516720eab: Pulling fs layer
48c198af87a5: Pulling fs layer
2c3cedab13cc: Pulling fs layer
0f7f40c17105: Pulling fs layer
5abdabbaa25b: Pulling fs layer
6977c39a1163: Pulling fs layer
f1828522c70b: Pulling fs layer
cbf4763b830e: Pulling fs layer
234b358f066d: Pulling fs layer
b891b67a5cf8: Waiting
ac1d0cb433aa: Waiting
c29a5135f832: Waiting
4f4fb700ef54: Waiting
1ff4f1de0bc5: Waiting
673864f86d20: Waiting
7b45c0976273: Waiting
ca9e486aa247: Waiting
0a97e5ce4743: Waiting
bc3ffa5c64c8: Waiting
e60516720eab: Waiting
48c198af87a5: Waiting
2c3cedab13cc: Waiting
0f7f40c17105: Waiting
5abdabbaa25b: Waiting
6977c39a1163: Waiting
f1828522c70b: Waiting
cbf4763b830e: Waiting
234b358f066d: Waiting
4df97d18a516: Waiting
79fe85183306: Waiting
d9d8e1823c6f: Download complete
4df97d18a516: Verifying Checksum
4df97d18a516: Download complete
79fe85183306: Download complete
84f2e2edb76d: Verifying Checksum
84f2e2edb76d: Download complete
ac1d0cb433aa: Download complete
c29a5135f832: Verifying Checksum
c29a5135f832: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
1ff4f1de0bc5: Verifying Checksum
1ff4f1de0bc5: Download complete
bccd10f490ab: Verifying Checksum
bccd10f490ab: Download complete
7b45c0976273: Verifying Checksum
7b45c0976273: Download complete
ca9e486aa247: Verifying Checksum
ca9e486aa247: Download complete
bccd10f490ab: Pull complete
d9d8e1823c6f: Pull complete
0a97e5ce4743: Verifying Checksum
0a97e5ce4743: Download complete
84f2e2edb76d: Pull complete
4df97d18a516: Pull complete
79fe85183306: Pull complete
bc3ffa5c64c8: Verifying Checksum
bc3ffa5c64c8: Download complete
e60516720eab: Download complete
48c198af87a5: Verifying Checksum
48c198af87a5: Download complete
2c3cedab13cc: Verifying Checksum
2c3cedab13cc: Download complete
0f7f40c17105: Verifying Checksum
0f7f40c17105: Download complete
5abdabbaa25b: Download complete
6977c39a1163: Verifying Checksum
6977c39a1163: Download complete
f1828522c70b: Verifying Checksum
f1828522c70b: Download complete
cbf4763b830e: Verifying Checksum
cbf4763b830e: Download complete
234b358f066d: Verifying Checksum
234b358f066d: Download complete
673864f86d20: Verifying Checksum
673864f86d20: Download complete
b891b67a5cf8: Download complete
b891b67a5cf8: Pull complete
ac1d0cb433aa: Pull complete
c29a5135f832: Pull complete
4f4fb700ef54: Pull complete
1ff4f1de0bc5: Pull complete
673864f86d20: Pull complete
7b45c0976273: Pull complete
ca9e486aa247: Pull complete
0a97e5ce4743: Pull complete
bc3ffa5c64c8: Pull complete
e60516720eab: Pull complete
48c198af87a5: Pull complete
2c3cedab13cc: Pull complete
0f7f40c17105: Pull complete
5abdabbaa25b: Pull complete
6977c39a1163: Pull complete
f1828522c70b: Pull complete
cbf4763b830e: Pull complete
234b358f066d: Pull complete
Digest: sha256:8616a3e0ad0554aa26c838819a8cf3e72ae600071c2e9e76e0fd6e32a8c97627
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.11:v1.23.0
docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.0
2024-04-27T11:50:48.789 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.23.0
2024-04-27T11:50:48.79 Pulled image for ddev/ddev-ssh-agent:v1.23.0
2024-04-27T11:50:48.792 Pulled image for ddev/ddev-traefik-router:v1.23.0
Building project images...
2024-04-27T11:50:48.887 Executing docker-compose -f /datas/phpstormProjects/tryddevproject-5461/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
...........Project images built in 11s.
2024-04-27T11:50:59.917 Executing docker-compose -f /datas/phpstormProjects/tryddevproject-5461/.ddev/.ddev-docker-compose-full.yaml up -d
 Network ddev-tryddevproject-5461_default  Created
 Container ddev-tryddevproject-5461-db  Created
 Container ddev-tryddevproject-5461-web  Created
 Container ddev-tryddevproject-5461-web  Started
 Container ddev-tryddevproject-5461-db  Started
2024-04-27T11:51:05.89 Copied /home/ridha/.local/share/mkcert:CopyIntoVolume_zhttywhuuafj into /mnt/v/mkcert in 321.110507ms
2024-04-27T11:51:06.189 Exec chown -R 1000 /mnt/v/mkcert stdout=, stderr=, err=<nil>
2024-04-27T11:51:07.239 Pushed mkcert rootca certs to ddev-global-cache/mkcert
2024-04-27T11:51:07.239 VIRTUAL_HOST=tryddevproject-5461.ddev.site for web
2024-04-27T11:51:07.239 HTTP_EXPOSE=80:80,8025:8025 for web
2024-04-27T11:51:07.239 HTTPS_EXPOSE=443:80,8026:8025 for web
2024-04-27T11:51:10.732 Copied /datas/phpstormProjects/tryddevproject-5461/.ddev/traefik:CopyIntoVolume_yubgznmxpcuz into /mnt/v/traefik in 177.33718ms
2024-04-27T11:51:10.854 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-04-27T11:51:11.504 Copied Traefik certs in /datas/phpstormProjects/tryddevproject-5461/.ddev/traefik/certs to ddev-global-cache/traefik
2024-04-27T11:51:11.508 Running /start.sh in ddev-webserver
Waiting for web/db containers to become ready: [web db]
2024-04-27T11:51:28.983 Copied /home/ridha/.ddev/commands:CopyIntoVolume_tfwictmgoeqe into /mnt/v/global-commands in 124.911309ms
2024-04-27T11:51:29.086 Exec chown -R 1000 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2024-04-27T11:51:29.796 Testing to see if /mnt/ddev_config is properly mounted
Starting ddev-router if necessary...
2024-04-27T11:51:31.842 Copied /home/ridha/.ddev/traefik:CopyIntoVolume_cjactquqcrdo into /mnt/v/traefik in 129.174858ms
2024-04-27T11:51:31.924 Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-04-27T11:51:32.297 Copied global Traefik config in /home/ridha/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Created
 Container ddev-router  Started
2024-04-27T11:51:33.56 Waiting for ddev-router to become ready. docker inspect --format "{{json .State.Health }}" ddev-router
2024-04-27T11:51:35.063 ddev-router is ready
Waiting for additional project containers to become ready...
All project containers are now ready.
Successfully started tryddevproject-5461
Project can be reached at https://tryddevproject-5461.ddev.site https://127.0.0.1:60002


======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:-HTTP/1.1 200 OK
Server: nginx
Date: Sat, 27 Apr 2024 10:51:38 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

-:-- --:--:-- --:--:--     0


======== curl -I of http://tryddevproject-5461.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Sat, 27 Apr 2024 10:51:38 GMT
Server: nginx
Vary: Accept-Encoding



======== Full curl of http://tryddevproject-5461.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0  28069      0 --:--:-- --:--:-- --:--:-- 33000
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Full curl of https://tryddevproject-5461.ddev.site from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   198    0   198    0     0   2380      0 --:--:-- --:--:-- --:--:--  2385
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/tmp/ddev-debug-test.txt</b><br />
file:///tmp/ddev-debug-test.txt<br />


======== Project ownership on host ========
drwxr-xr-x. 1 ridha ridha 16 27 avril 11:46 ../tryddevproject-5461


======== Project ownership in container ========
drwxr-xr-x. 1 ridha ridha 16 Apr 27 10:46 //var/www/html


======== In-container filesystem ========
Filesystem     Type  1K-blocks      Used Available Use% Mounted on
/dev/sda3      btrfs 232766464 208215924  21641180  91% /var/www/html


======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting 10 seconds to run ddev stop --unlist
Ouverture dans une session de navigateur existante.
running ddev stop --unlist
 Container ddev-tryddevproject-5461-db  Stopped
 Container ddev-tryddevproject-5461-web  Stopped
 Container ddev-tryddevproject-5461-db  Stopped
 Container ddev-tryddevproject-5461-web  Stopped
 Container ddev-tryddevproject-5461-db  Removed
 Container ddev-tryddevproject-5461-web  Removed
 Network ddev-tryddevproject-5461_default  Removed
Project tryddevproject-5461 has been stopped.
```
</details>

### Expected Behavior

Ddev start fine

### Actual Behavior

Hy

I have this error  when wtith ddev start command on magento 2 project. It worked fine with version 1.21.6 but now it crashes with version 1.23.0
Error:

Failed waiting for web/db containers to become ready: web container failed: log=&{2024-04-27 11:35:48.176860575 +0100 CET 2024-04-27 11:35:49.349035849 +0100 CET 143 php-fpm:FATAL Shut down
}, err=ddev-m246-web container is unhealthy: &{2024-04-27 11:35:48.176860575 +0100 CET 2024-04-27 11:35:49.349035849 +0100 CET 143 php-fpm:FATAL Shut down
}, more info with [
        ddev logs -s web
        docker logs ddev-m246-web
        docker inspect --format "{{ json .State.Health }}" ddev-m246-web | docker run -i --rm ddev/ddev-utilities jq -r
] 

Thanks

**Comment by rfay** [comment] 2024-04-27 15:21
First some comments that may help. 

* `Project should most often be in a subdirectory of the user's home directory.
Instead it's in /datas/phpstormProjects/lcgpro_prod_2.4.6-p4` - It really is better to use your home directory for projects. Everything on Linux is set up to expect that work of this type will be in your home dir. Obviously you've been making this work for some time, so that's not related to this problem.
* You have a `.ddev/config.m246.yaml` - what's in it? Why is it there? Is it checked in?
* You're running a script called `check-ddev-version.sh`. I recommend that you start using [ddev_version_constraint](https://ddev.readthedocs.io/en/stable/users/configuration/config/#ddev_version_constraint)
* Do you have a `.ddev/web-build/Dockerfile.*` ? that could be related here. Please try removing it 


Now for the actual problem, it appears that php-fpm is crashing: "php-fpm:FATAL Shut down". this is going to be a result of local configuration.

Please try removing custom config and then reintroducing it to find out what the issue is.

**Comment by zimbar** [comment] 2024-04-27 15:48
Hy

I removed .ddev/web-build/Dockerfile and it works now.

Thanks

**Comment by rfay** [comment] 2024-04-27 15:52
Please show me what you had in the Dockerfile, thanks. I'll explain what went wrong.

**Comment by zimbar** [comment] 2024-04-27 15:54
ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN disable_xdebug
RUN if [ ! -f /usr/bin/sed ]; then ln -sf /bin/sed /usr/bin/sed; fi
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends --no-install-suggests build-essential make autoconf libc-dev pkg-config php-dev php-pear zlib1g-dev libmemcached-dev
RUN sudo chmod -R 664  $(pecl config-get php_dir)
# The "echo" below just forces accepting the "automatic" configuration, the same as hitting <RETURN>
RUN echo | sudo pecl install memcached-3.2.0

Thanks

**Comment by rfay** [comment] 2024-04-27 16:01
It looks like your goal was to install a specific version of memcached? Do you still need to do that anyway? DDEV v1.23.0 ships with php-memcached `3.2.0`

Some comments if you continue with this:
* There's no need for `RUN disable_xdebug`, it's off by default
* `ARG BASE_IMAGE` and `FROM $BASE_IMAGE` are no longer required in recent versions of DDEV.
* I don't know why you'd symlink sed, but doubt it does any harm.

**Closed by rfay** 2024-04-27 16:01 UTC

**Comment by zimbar** [comment] 2024-04-27 16:04
Thanks for your reponse
