### ISSUE TITLE
Update Drupal 7 included Drush version to Drush 8.4.11

### ISSUE THREAD

**Issue by mbomb007** [ddev/ddev#4189] opened 2022-09-07 18:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

The Drupal 7 project image is bundled with Drush 8.4.8. If trying to use PHP 8, I receive PHP warnings when using Drush. They are fixed in 8.4.11.

```bash
$ ddev version
 ITEM             VALUE                                   
 DDEV version     v1.21.1                                 
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.20.0 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.20.0             
 docker           20.10.17                                
 docker-compose   v2.9.0                                  
 docker-platform  GN27RP2-7060                            
 mutagen          0.15.1                                  
 os               linux                                   
 router           drud/ddev-router:v1.20.0                
 web              drud/ddev-webserver:20220808_yarn_crash 
```

```bash
$ ddev . drush version
PHP Deprecated:  Return type of DrushBatchContext::offsetSet($name, $value) should either be compatible with ArrayObject::offsetSet(mixed $key, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/drush8/includes/batch.inc on line 39

Deprecated: Return type of DrushBatchContext::offsetSet($name, $value) should either be compatible with ArrayObject::offsetSet(mixed $key, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/drush8/includes/batch.inc on line 39
 Drush Version   :  8.4.8 
```

### Current Behavior

I receive PHP deprecation warnings when running Drush for Drupal 7 with PHP 8+.

### Expected Behavior

No warnings

### Steps To Reproduce

I receive PHP deprecation warnings when running Drush for Drupal 7 with PHP 8+.

```yaml
type: drupal7
docroot: ""
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
database:
  type: mariadb
  version: "10.5"
nfs_mount_enabled: false
mutagen_enabled: false
omit_containers: [dba]
use_dns_when_possible: true
composer_version: "2"
web_environment:
- max_input_vars=3000
nodejs_version: "16"
```

**Comment by rfay** [comment] 2022-09-07 19:54
Unfortunately, while drush 8.4.11 works for php 8.0+, it doesn't work for php7.*, which is why drush was explicitly downgraded.

See:

* https://github.com/drud/ddev/pull/3882
* https://github.com/drush-ops/drush/issues/4979

I'd love for the drush problem to be fixed; there are other paths forward for this as well. 
* You could install drush in a post-start hook or a .ddev/web-build/Dockerfile.* and link it for your project.
* drush 8.4.11 could be linked for php8+ and drupal7. I'm not sure that's all that worthy, but we'll see if anybody chimes in.

**Comment by rfay** [comment] 2022-09-07 20:44
Well, the reason that global drush is done for drupal6/7 is that they mostly don't have composer. So your D7 site may have a composer.json but most don't. 

However, I've never experimented with a composer global command. You might be able to do a `ddev exec` instead, but overall I think you'd be happier with a .ddev/web-build/Dockerfile.drush

**Comment by rfay** [comment] 2022-09-07 20:55
PATH is an environment variable, which means it doesn't persist anywhere. You can set it other ways if you want to change it everywhere, see https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#altering-the-in-container-path

But the easiest thing is to add a symlink to somewhere that's already in the $PATH, like /usr/local/bin or `<approot>/bin`

**Comment by rfay** [comment] 2022-09-07 21:45
You could do it in one line with `ln -sf "$HOME/.composer/vendor/drush/drush/drush" /usr/local/bin/drush`

**Comment by rfay** [comment] 2022-09-18 09:57
I'm happy to reopen this and move to a newer drush when there's progress in 
* https://github.com/drush-ops/drush/issues/4979

Closing for now.

**Comment by rfay** [comment] 2023-03-15 16:28
Drush 8.4.12 is out, hopefully can solve the issues here.

**Comment by greg-1-anderson** [comment] 2023-03-15 16:34
I missed the `@`-mention of me here last year; my git notifications are like a waterfall, I have to be fast to catch things. Please let me know if you are having continuing problems with Drush 8 and PHP 7.

Right now, the Drush test suite is running on:
- 8.2
- 8.1
- 8.0
- 7.4
- 5.6

All tests are green. If there are use-cases that are not covered by tests that are failing, I'm happy to look into it and roll another release.

**Comment by greg-1-anderson** [comment] 2023-03-15 16:38
I see I did interact with this problem back in https://github.com/drush-ops/drush/issues/4979, but I'm still not sure what the problem is. Maybe it was a bug in Box; I upgraded to a new Box release to build the latest phar, so let's hope that solves the problem. If not, maybe switch your ddev Drush packaging script to `git clone` + `composer install`?

**Comment by rfay** [comment] 2023-03-15 16:40
Thanks @greg-1-anderson - it could in fact change. Drush is only used globally in Drupal6/7 configs in DDEV, so it's certainly easier to use the packaged version there. But I imagine `composer install --global` would work, although probably slow down the build a bit.

**Closed** 2023-03-16 14:42 UTC

**Comment by greg-1-anderson** [comment] 2023-03-16 17:18
[Don't use composer --global require](https://pantheon.io/blog/fixing-composer-global-command)! 😄  You don't need to use cgr either; that would make the build even slower. If the phar is working, then there's no need to make any changes. If you want to eliminate the Box wrappers, though, you could:
```
git clone https://github.com/drush-ops/drush.git --branch=$VERSION /path/to/drush
cd /path/to/drush
composer install --no-dev
```
Then make a symlink to `/path/to/drush/drush`.

**Comment by greg-1-anderson** [comment] 2023-03-16 17:20
The alternative to `composer --global require` that's not cgr is [documented in the cgr README](https://github.com/consolidation/cgr#manual-use-of-native-composer-features).

**Comment by rfay** [comment] 2023-03-16 17:38
Thanks @greg-1-anderson - The box-packaged version seems to work OK and was implemented in 
* https://github.com/ddev/ddev/pull/4754
