### ISSUE TITLE
Set static IP address for a container.

### ISSUE THREAD

**Issue by seebeen** [ddev/ddev#6376] opened 2024-07-04 19:21 UTC
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

Irrelevant to the discussion at hand

### Expected Behavior

I wanted to set a specific IP range for a project, and have the web container in that project always have the same IP in the network.

### Actual Behavior

Project got the defined IP range, the network changes for the web container were not applied.

### Steps To Reproduce

File: docker-compose.communicate.yaml

```docker-compose
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24 # Or any available range
```

File: docker-compose.web.yaml
```docker-compose
services:
  web:
    networks:
      default:
        ipv4_address: 172.20.0.8
      ddev_default: null
```

### Anything else?

Network section in file `.ddev-docker-compose-full.yaml` is:

```docker-compose
networks:
  ddev_default: null
  default: null
```

So - for some reason, the network section always remains at the default value.

**Comment by stasadev** [comment] 2024-07-04 21:16
Related:

- https://github.com/ddev/ddev/issues/5706#issuecomment-1899150708

We currently do not allow modification of the `networks` stanza.

**Comment by seebeen** [comment] 2024-07-05 07:25
Can that be overriden somehow.?

**Comment by stasadev** [comment] 2024-07-05 11:20
> Can that be overriden somehow.?

Only if the underlying Go code is modified in some way.

The problem is that there is no SDK for the docker-compose API library for Go, and we run `docker-compose config` as is (which lacks the necessary flexibility) to build the resulting `.ddev/.ddev-docker-compose-full.yaml` file.

**Comment by seebeen** [comment] 2024-07-09 15:06
Is the underlying go code ours or we rely on external lib. Can you point me in a direction? :)

**Comment by stasadev** [comment] 2024-07-09 15:10
Of course, this is our code https://github.com/ddev/ddev/blob/79fa0954fe41706a6335477cb9d70fe07d145c75/pkg/ddevapp/compose_yaml.go#L126-L130

And discussion about it https://github.com/ddev/ddev/pull/3620/files#r815353519

**Comment by rfay** [comment] 2024-07-09 15:26
@seebeen maybe you could say what you're trying to accomplish. Why do you want to set a specific address for a container? That won't usually work in different docker environments, different machines, different team members, different projects.

**Comment by seebeen** [comment] 2024-07-09 20:08
I have two web services which aren't developed by me and they need to talk to one another.
Unfortunately, I cannot whitelist by CIDR on one of them so I need to whitelist a specific IP.

When the IP changes there is no two-way communication so both apps are in a semi-broken state.

Having an option to lock the IP for a container saves me time because I do not need to reconfigure the app.

And since I'm using DDEV in a production environment - it can be a hassle.

**Comment by rfay** [comment] 2024-07-09 20:35
You can't use hostname at all, just IP?

**Comment by rfay** [comment] 2024-07-09 20:49
Could you use the router with a TCP proxy?

**Comment by rfay** [comment] 2024-07-18 21:33
I don't expect to address this, but if you want to see if you can experiment with a PR, we'll certainly support you. Closing for now.

**Closed** 2024-07-29 00:10 UTC

**Comment by rfay** [comment] 2024-09-03 23:09
@seebeen  if you respond in 
* https://github.com/ddev/ddev/pull/6501

and take a look at that PR it may have a chance to go in. Otherwise, that PR may not have a future. 

If it's not important to you any more, please just say so.
