### ISSUE TITLE
No internet in Docker container after upgrade with Traefik router

### ISSUE THREAD

**Issue by SvenVdv** [ddev/ddev#5218] opened 2023-08-01 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project stad: [/home/sven/projects/drupal_site_stadgent/.ddev/config.yaml]
name: stad
type: drupal9
docroot: web
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.0
router_http_port: 8080
router_https_port: 8443
additional_hostnames: []
additional_fqdns: [local.stad.gent]
database: {mysql 5.7}
performance_mode: mutagen
hooks: map[pre-start:[map[exec-host:sudo apachectl stop]]]
mailhog_port: 8025
mailhog_https_port: 8026
webimage_extra_packages: [php8.1-gmp php-imagick webp]
project_tld: ddev.site
composer_version: 2
nodejs_version: 18
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-25033 in ../tryddevproject-25033 =========
OS Information: Linux CP107281 5.15.90.3-microsoft-standard-WSL2 #1 SMP Wed Jul 12 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(sven) gid=1000(sven) groups=1000(sven),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),116(netdev),999(docker)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.22.0
 architecture     amd64
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0
 docker           24.0.5
 docker-compose   v2.20.0
 docker-platform  wsl2-docker-ce
 mutagen          0.17.2
 os               linux
 router           traefik:v2.10
 web              ddev/ddev-webserver:v1.22.0
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.20.0
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35927416 Jul 21 22:35 /usr/bin/docker
docker version:
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
--------------------------------------------------------------------------------
Name: stad
Identifier: sync_NYPDd4JdGfZDVTTNvVYMT8RjLv7yct4nFYHDQaDrWts
Labels:
        com.ddev.config-hash: c212281329fb24762a96e1b7a37a19ed84868866
        com.ddev.volume-signature: var-run-1690879010
Configuration:
        Synchronization mode: Two Way Resolved
        Hashing algorithm: Default (SHA-1)
        Maximum allowed entry count: Default (2⁶⁴−1)
        Maximum staging file size: Default (18 EB)
        Symbolic link mode: POSIX Raw
        Ignore VCS mode: Default (Propagate)
        Ignores:
                /.git
                /.tarballs
                /.ddev/db_snapshots
                /.ddev/.importdb*
                .DS_Store
                .idea
                /web/sites/default/files
        Permissions mode: Default (Portable)
Alpha:
        URL: /home/sven/projects/drupal_site_stadgent
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
        Connected: Yes
        Synchronizable contents:
                17102 directories
                70670 files (492 MB)
                102 symbolic links
Beta:
        URL: docker://ddev-stad-web/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Configuration:
                Watch mode: Default (Portable)
                Watch polling interval: Default (10 seconds)
                Probe mode: Default (Probe)
                Scan mode: Default (Accelerated)
                Stage mode: Neighboring
                File mode: Default (0600)
                Directory mode: Default (0700)
                Default file/directory owner: Default
                Default file/directory group: Default
                Compression: Default (DEFLATE)
        Connected: Yes
        Synchronizable contents:
                17102 directories
                70670 files (492 MB)
                102 symbolic links
Status: Watching for changes
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: wsl2-docker-ce 
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.20.0
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 24.0.5
Able to run simple container that mounts a volume. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G     22.4G    933.2G   2% /

unable to create project at project root '/home/sven/projects/test': project root /home/sven/projects/test does not exist
unable to create project at project root '/home/sven/projects/tester': project root /home/sven/projects/tester does not exist
 Container ddev-stad-varnish  Stopped
 Container ddev-stad-solr  Stopped
 Container ddev-stad-db  Stopped
 Container ddev-stad-web  Stopped
 Container ddev-stad-solr  Stopped
 Container ddev-stad-db  Stopped
 Container ddev-stad-varnish  Stopped
 Container ddev-stad-solr  Removed
 Container ddev-stad-db  Removed
 Container ddev-stad-varnish  Removed
 Container ddev-stad-web  Stopped
 Container ddev-stad-web  Removed
 Network ddev-stad_default  Removed
Project stad has been stopped.
Stopped mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers: 
CONTAINER ID   IMAGE         COMMAND                  CREATED      STATUS                  PORTS     NAMES
34826d0e7994   nginx         "/docker-entrypoint.…"   4 days ago   Exited (0) 4 days ago             naughty_pasteur
e65d7844ff55   nginx         "/docker-entrypoint.…"   4 days ago   Created                           lucid_herschel
b1fbe80d5416   nginx         "/docker-entrypoint.…"   4 days ago   Exited (0) 4 days ago             zen_cohen
4f18907aa670   hello-world   "/hello"                 4 days ago   Exited (0) 4 days ago             laughing_volhard
afef94b967ed   busybox       "nslookup google.com"    6 days ago   Exited (1) 6 days ago             keen_bouman
2767e73cba8e   busybox       "nslookup google.com"    6 days ago   Exited (1) 6 days ago             elastic_brattain
Network ddev_default created 
Starting tryddevproject-25033... 
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
unable to determine WSL2 host.docker.internal because /etc/resolv.conf is not available or not auto-generated 
unable to determine WSL2 host.docker.internal because /etc/resolv.conf is not available or not auto-generated
v1.22.0: Pulling from ddev/ddev-dbserver-mariadb-10.4
0fb668748fc8: Already exists
11f65aacc004: Already exists
f3ccf0f0c34f: Already exists
ab42338ab2d0: Already exists
c807600eb677: Already exists
debe5f4c6a9b: Already exists
91a3dfd98bfe: Already exists
522a2cacfb45: Already exists
a31ae496b1e5: Already exists
4f4fb700ef54: Already exists
ec28e4f24a45: Already exists
ee09bc14631b: Already exists
e25ac0367bb3: Already exists
74a6e7288747: Already exists
3d507dd19929: Already exists
17481026acee: Already exists
9d0a0d58a087: Already exists
8d27964fd3b0: Already exists
8772df3cc945: Already exists
ca95039c7315: Already exists
ac484e3d8702: Already exists
5b1edb6d2ecd: Already exists
6c0f9257cdce: Already exists
d7706094646c: Already exists
Digest: sha256:aecfb2180c10c1af0f4503904b44839cd38c8183b69d9428863ddafa14f8b2c1
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.4:v1.22.0
docker.io/ddev/ddev-dbserver-mariadb-10.4:v1.22.0
 Network ddev-tryddevproject-25033_default  Created 
 Container ddev-tryddevproject-25033-web  Created 
 Container ddev-tryddevproject-25033-db  Created 
 Container ddev-tryddevproject-25033-web  Started 
 Container ddev-tryddevproject-25033-db  Started 
failed to solve: process "/bin/sh -c apk add bash curl htop vim" did not complete successfully: exit code: 4 
Failed to start tryddevproject-25033: failed to start ddev-router: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-tryddevproject-25033 docker-compose -f /home/sven/.ddev/.router-compose-full.yaml -p ddev-router up --build -
d', action='[-p ddev-router up --build -d]', err='exit status 17', stdout='#1 [ddev-router internal] load build definition from Dockerfile
#1 transferring dockerfile: 206B done
#1 DONE 0.0s

#2 [ddev-router internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [ddev-router internal] load metadata for docker.io/library/traefik:v2.10
#3 DONE 0.0s

#4 [ddev-router 1/4] FROM docker.io/library/traefik:v2.10
#4 CACHED

#5 [ddev-router internal] load build context
#5 transferring context: 1.07kB done
#5 DONE 0.0s

#6 [ddev-router 2/4] RUN apk add bash curl htop vim
#6 0.226 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
#6 0.226 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: DNS lookup error
#6 0.226 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
#6 0.226 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/community: DNS lookup error
#6 0.226 ERROR: unable to select packages:
#6 0.226   bash (no such package):
#6 0.226     required by: world[bash]
#6 0.226   curl (no such package):
#6 0.226     required by: world[curl]
#6 0.227   htop (no such package):
#6 0.227     required by: world[htop]
#6 0.227   vim (no such package):
#6 0.227     required by: world[vim]
#6 ERROR: process "/bin/sh -c apk add bash curl htop vim" did not complete successfully: exit code: 4
------
 > [ddev-router 2/4] RUN apk add bash curl htop vim:
0.226 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/community: DNS lookup error
0.226 ERROR: unable to select packages:
0.226   bash (no such package):
0.226     required by: world[bash]
0.226   curl (no such package):
0.226     required by: world[curl]
0.227   htop (no such package):
0.227     required by: world[htop]
0.227   vim (no such package):
0.227     required by: world[vim]
------
', stderr='failed to solve: process "/bin/sh -c apk add bash curl htop vim" did not complete successfully: exit code: 4' 
unable to create project at project root '/home/sven/projects/test': project root /home/sven/projects/test does not exist
unable to create project at project root '/home/sven/projects/tester': project root /home/sven/projects/tester does not exist
┌──────────────────────┬─────────┬─────────────────────────────────┬────────────────────────────────────────┬─────────┐
│ NAME                 │ STATUS  │ LOCATION                        │ URL                                    │ TYPE    │
├──────────────────────┼─────────┼─────────────────────────────────┼────────────────────────────────────────┼─────────┤
│ stad                 │ stopped │ ~/projects/drupal_site_stadgent │                                        │ drupal9 │
├──────────────────────┼─────────┼─────────────────────────────────┼────────────────────────────────────────┼─────────┤
│ tryddevproject-25033 │ OK      │ ~/projects/tryddevproject-25033 │ https://tryddevproject-25033.ddev.site │ php     │
├──────────────────────┼─────────┼─────────────────────────────────┼────────────────────────────────────────┼─────────┤
│ Router               │ stopped │ ~/.ddev                         │ http://localhost:9999                  │ traefik │
└──────────────────────┴─────────┴─────────────────────────────────┴────────────────────────────────────────┴─────────┘

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Project: tryddevproject-25033 ~/projects/tryddevproject-25033 https://tryddevproject-25033.ddev.site                               │
│ Docker platform: wsl2-docker-ce                                                                                                    │
│ Router: traefik                                                                                                                    │
├──────────┬──────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┤
│ SERVICE  │ STAT │ URL/PORT                                                                                    │ INFO               │
├──────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ web      │ OK   │ https://tryddevproject-25033.ddev.site                                                      │ php PHP8.1         │
│          │      │ InDocker: web:80,8025,443                                                                   │ nginx-fpm          │
│          │      │ Host: 127.0.0.1:32855,32856                                                                 │ docroot:'web'      │
│          │      │                                                                                             │ NodeJS:18          │
├──────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ db       │ OK   │ InDocker: db:3306                                                                           │ mariadb:10.4       │
│          │      │ Host: 127.0.0.1:32857                                                                       │ User/Pass: 'db/db' │
│          │      │                                                                                             │ or 'root/root'     │
├──────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Mailhog  │      │ MailHog: https://tryddevproject-25033.ddev.site:8026                                        │                    │
│          │      │ `ddev launch -m`                                                                            │                    │
├──────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ All URLs │      │ https://tryddevproject-25033.ddev.site, https://127.0.0.1:32855,                            │                    │
│          │      │ http://tryddevproject-25033.ddev.site, http://127.0.0.1:32856                               │                    │
└──────────┴──────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┘

============= ddev-tryddevproject-25033-web healtcheck run =========
+ for f in /etc/bashrc/*.bashrc
+ source /etc/bashrc/commandline-addons.bashrc
++ export 'PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin:/var/www/html/vendor/bin'
++ PATH='~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin:/var/www/html/vendor/bin'
++ '[' -s /home/sven/.nvm/nvm.sh ']'
++ '[' -s /home/sven/.nvm/bash_completion ']'
++ '[' php = python ']'
++ '[' php = django4 ']'
++ ls '/home/sven/.bashrc.d/*'
bash: rm -f /tmp/healthy && /healthcheck.sh: No such file or directory
============= ddev logs =========
+ logpipe=/var/tmp/logpipe
+ [[ ! -p /var/tmp/logpipe ]]
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
2023-08-01 09:46:57,898 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2023-08-01 09:46:57,898 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2023-08-01 09:46:57,898 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2023-08-01 09:46:57,900 INFO RPC interface 'supervisor' initialized
2023-08-01 09:46:57,900 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-08-01 09:46:57,900 INFO supervisord started with pid 32
2023-08-01 09:46:58,908 INFO spawned: 'child_exit_monitor' with pid 1922
2023-08-01 09:46:58,909 INFO spawned: 'php-fpm' with pid 1923
2023-08-01 09:46:58,910 INFO spawned: 'nginx' with pid 1924
2023-08-01 09:46:58,911 INFO spawned: 'mailhog' with pid 1925
[01-Aug-2023 09:46:58] NOTICE: fpm is running, pid 1923
[01-Aug-2023 09:46:58] NOTICE: ready to handle connections
[01-Aug-2023 09:46:58] NOTICE: systemd monitor interval set to 10000ms
2023-08-01 09:46:59,957 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-01 09:46:59,957 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-01 09:46:59,957 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-01 09:46:59,957 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
============= contents of /mnt/ddev_config  =========
Error response from daemon: No such container: ddev-d9-db
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 01 Aug 2023 09:47:02 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-25033.ddev.site from outside:
curl: (7) Failed to connect to tryddevproject-25033.ddev.site port 80 after 18 ms: Connection refused
Unable to curl the requested project Please provide this output in a new gist at gist.github.com.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-25033'
Failed running test_ddev.sh: exit status 1
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh` 

```
</details>         

### Expected Behavior

I expected ddev-router to start normally

### Actual Behavior

It did not. Instead it does not have an internet connection

### Steps To Reproduce

1. On Windows WSL2, behind a VPN
2. Upgraded to 1.22.0
3. /etc/resolv.conf is generated via a script that checks the vpn nameservers
4. I added the link of my local host to the url in Windows in my hosts file (C:\Windows\System32\drivers\etc\hosts)
5. If I try nginx-proxy I do get internet in the container but I don't get a connection in the browser (ERR_CONNECTION_REFUSED)
6. If I try Traefik I get the error you can see in the debug test, which (I think) says that I don't have internet in my Docker container

PS: I'm sorry for the n00b way of describing the problem, I'm a frontender trying to fix the issue. It already took me a day to figure out it was Traefik/router-related 😄

**Comment by SvenVdv** [comment] 2023-08-01 12:04
Just saw that there's a duplicate in #5209

**Comment by rfay** [comment] 2023-08-01 12:09
Yes, as in #5209, you'll need to talk to your IT department. I'm happy to help you sort it out, and happy to do a live debugging session with you over in [discord](https://[discord](https://discord.gg/hCZFfAMc5k).gg/hCZFfAMc5k). If your problem is the same, it's that you have an intrusive VPN that requires significant workaround to do a docker build. Happy to continue the conversation here or elsewhere, happy to do a live debugging session with you. But I think you need your IT department involved if you've described it completely.

**Comment by rfay** [comment] 2023-08-01 12:09
Closed as (described) duplicate of
* #5209

**Closed by rfay** 2023-08-01 12:09 UTC

**Comment by rfay** [comment] 2023-08-01 13:57
I note that this can also be caused by network trouble and it looks the same; may also be upstream server trouble:

```
#6 0.151 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
  | #6 0.439 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: IO ERROR
 ```

Here the attempt to access the alpinelinux CDN failed
